// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht/bits"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
	"go.uber.org/zap"
)

// NewMockPeerDownloader creates a new instance of MockPeerDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerDownloader {
	mock := &MockPeerDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerDownloader is an autogenerated mock type for the PeerDownloader type
type MockPeerDownloader struct {
	mock.Mock
}

type MockPeerDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerDownloader) EXPECT() *MockPeerDownloader_Expecter {
	return &MockPeerDownloader_Expecter{mock: &_m.Mock}
}

// DownloadFromPeers provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) DownloadFromPeers(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest) ([]byte, error) {
	ret := _mock.Called(ctx, hash, hashBitmap, req)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFromPeers")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) ([]byte, error)); ok {
		return returnFunc(ctx, hash, hashBitmap, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) []byte); ok {
		r0 = returnFunc(ctx, hash, hashBitmap, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) error); ok {
		r1 = returnFunc(ctx, hash, hashBitmap, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerDownloader_DownloadFromPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFromPeers'
type MockPeerDownloader_DownloadFromPeers_Call struct {
	*mock.Call
}

// DownloadFromPeers is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - hashBitmap bits.Bitmap
//   - req *blob.BlobRequest
func (_e *MockPeerDownloader_Expecter) DownloadFromPeers(ctx interface{}, hash interface{}, hashBitmap interface{}, req interface{}) *MockPeerDownloader_DownloadFromPeers_Call {
	return &MockPeerDownloader_DownloadFromPeers_Call{Call: _e.mock.On("DownloadFromPeers", ctx, hash, hashBitmap, req)}
}

func (_c *MockPeerDownloader_DownloadFromPeers_Call) Run(run func(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest)) *MockPeerDownloader_DownloadFromPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bits.Bitmap
		if args[2] != nil {
			arg2 = args[2].(bits.Bitmap)
		}
		var arg3 *blob.BlobRequest
		if args[3] != nil {
			arg3 = args[3].(*blob.BlobRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPeerDownloader_DownloadFromPeers_Call) Return(bytes []byte, err error) *MockPeerDownloader_DownloadFromPeers_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPeerDownloader_DownloadFromPeers_Call) RunAndReturn(run func(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest) ([]byte, error)) *MockPeerDownloader_DownloadFromPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxPeers provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) GetMaxPeers() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxPeers")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPeerDownloader_GetMaxPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxPeers'
type MockPeerDownloader_GetMaxPeers_Call struct {
	*mock.Call
}

// GetMaxPeers is a helper method to define mock.On call
func (_e *MockPeerDownloader_Expecter) GetMaxPeers() *MockPeerDownloader_GetMaxPeers_Call {
	return &MockPeerDownloader_GetMaxPeers_Call{Call: _e.mock.On("GetMaxPeers")}
}

func (_c *MockPeerDownloader_GetMaxPeers_Call) Run(run func()) *MockPeerDownloader_GetMaxPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDownloader_GetMaxPeers_Call) Return(n int) *MockPeerDownloader_GetMaxPeers_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPeerDownloader_GetMaxPeers_Call) RunAndReturn(run func() int) *MockPeerDownloader_GetMaxPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeout provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) GetTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockPeerDownloader_GetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeout'
type MockPeerDownloader_GetTimeout_Call struct {
	*mock.Call
}

// GetTimeout is a helper method to define mock.On call
func (_e *MockPeerDownloader_Expecter) GetTimeout() *MockPeerDownloader_GetTimeout_Call {
	return &MockPeerDownloader_GetTimeout_Call{Call: _e.mock.On("GetTimeout")}
}

func (_c *MockPeerDownloader_GetTimeout_Call) Run(run func()) *MockPeerDownloader_GetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDownloader_GetTimeout_Call) Return(duration time.Duration) *MockPeerDownloader_GetTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPeerDownloader_GetTimeout_Call) RunAndReturn(run func() time.Duration) *MockPeerDownloader_GetTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerDownloader_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockPeerDownloader_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockPeerDownloader_Expecter) IsStopped() *MockPeerDownloader_IsStopped_Call {
	return &MockPeerDownloader_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockPeerDownloader_IsStopped_Call) Run(run func()) *MockPeerDownloader_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDownloader_IsStopped_Call) Return(b bool) *MockPeerDownloader_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerDownloader_IsStopped_Call) RunAndReturn(run func() bool) *MockPeerDownloader_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogger provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) SetLogger(logger *zap.Logger) {
	_mock.Called(logger)
	return
}

// MockPeerDownloader_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockPeerDownloader_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *zap.Logger
func (_e *MockPeerDownloader_Expecter) SetLogger(logger interface{}) *MockPeerDownloader_SetLogger_Call {
	return &MockPeerDownloader_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockPeerDownloader_SetLogger_Call) Run(run func(logger *zap.Logger)) *MockPeerDownloader_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zap.Logger
		if args[0] != nil {
			arg0 = args[0].(*zap.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDownloader_SetLogger_Call) Return() *MockPeerDownloader_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_SetLogger_Call) RunAndReturn(run func(logger *zap.Logger)) *MockPeerDownloader_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetMaxConcurrency provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) SetMaxConcurrency(maxConcurrency int) {
	_mock.Called(maxConcurrency)
	return
}

// MockPeerDownloader_SetMaxConcurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxConcurrency'
type MockPeerDownloader_SetMaxConcurrency_Call struct {
	*mock.Call
}

// SetMaxConcurrency is a helper method to define mock.On call
//   - maxConcurrency int
func (_e *MockPeerDownloader_Expecter) SetMaxConcurrency(maxConcurrency interface{}) *MockPeerDownloader_SetMaxConcurrency_Call {
	return &MockPeerDownloader_SetMaxConcurrency_Call{Call: _e.mock.On("SetMaxConcurrency", maxConcurrency)}
}

func (_c *MockPeerDownloader_SetMaxConcurrency_Call) Run(run func(maxConcurrency int)) *MockPeerDownloader_SetMaxConcurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDownloader_SetMaxConcurrency_Call) Return() *MockPeerDownloader_SetMaxConcurrency_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_SetMaxConcurrency_Call) RunAndReturn(run func(maxConcurrency int)) *MockPeerDownloader_SetMaxConcurrency_Call {
	_c.Run(run)
	return _c
}

// SetMaxPeers provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) SetMaxPeers(maxPeers int) {
	_mock.Called(maxPeers)
	return
}

// MockPeerDownloader_SetMaxPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxPeers'
type MockPeerDownloader_SetMaxPeers_Call struct {
	*mock.Call
}

// SetMaxPeers is a helper method to define mock.On call
//   - maxPeers int
func (_e *MockPeerDownloader_Expecter) SetMaxPeers(maxPeers interface{}) *MockPeerDownloader_SetMaxPeers_Call {
	return &MockPeerDownloader_SetMaxPeers_Call{Call: _e.mock.On("SetMaxPeers", maxPeers)}
}

func (_c *MockPeerDownloader_SetMaxPeers_Call) Run(run func(maxPeers int)) *MockPeerDownloader_SetMaxPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDownloader_SetMaxPeers_Call) Return() *MockPeerDownloader_SetMaxPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_SetMaxPeers_Call) RunAndReturn(run func(maxPeers int)) *MockPeerDownloader_SetMaxPeers_Call {
	_c.Run(run)
	return _c
}

// SetTimeout provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) SetTimeout(timeout time.Duration) {
	_mock.Called(timeout)
	return
}

// MockPeerDownloader_SetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeout'
type MockPeerDownloader_SetTimeout_Call struct {
	*mock.Call
}

// SetTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockPeerDownloader_Expecter) SetTimeout(timeout interface{}) *MockPeerDownloader_SetTimeout_Call {
	return &MockPeerDownloader_SetTimeout_Call{Call: _e.mock.On("SetTimeout", timeout)}
}

func (_c *MockPeerDownloader_SetTimeout_Call) Run(run func(timeout time.Duration)) *MockPeerDownloader_SetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDownloader_SetTimeout_Call) Return() *MockPeerDownloader_SetTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_SetTimeout_Call) RunAndReturn(run func(timeout time.Duration)) *MockPeerDownloader_SetTimeout_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) Start() {
	_mock.Called()
	return
}

// MockPeerDownloader_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPeerDownloader_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPeerDownloader_Expecter) Start() *MockPeerDownloader_Start_Call {
	return &MockPeerDownloader_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPeerDownloader_Start_Call) Run(run func()) *MockPeerDownloader_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDownloader_Start_Call) Return() *MockPeerDownloader_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_Start_Call) RunAndReturn(run func()) *MockPeerDownloader_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockPeerDownloader
func (_mock *MockPeerDownloader) Stop() {
	_mock.Called()
	return
}

// MockPeerDownloader_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPeerDownloader_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPeerDownloader_Expecter) Stop() *MockPeerDownloader_Stop_Call {
	return &MockPeerDownloader_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPeerDownloader_Stop_Call) Run(run func()) *MockPeerDownloader_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDownloader_Stop_Call) Return() *MockPeerDownloader_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDownloader_Stop_Call) RunAndReturn(run func()) *MockPeerDownloader_Stop_Call {
	_c.Run(run)
	return _c
}
