// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/client"
	"go.lumeweb.com/liblbry/stream"
)

// NewMockStreamAcquirer creates a new instance of MockStreamAcquirer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamAcquirer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamAcquirer {
	mock := &MockStreamAcquirer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamAcquirer is an autogenerated mock type for the StreamAcquirer type
type MockStreamAcquirer struct {
	mock.Mock
}

type MockStreamAcquirer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamAcquirer) EXPECT() *MockStreamAcquirer_Expecter {
	return &MockStreamAcquirer_Expecter{mock: &_m.Mock}
}

// GetSDBlob provides a mock function for the type MockStreamAcquirer
func (_mock *MockStreamAcquirer) GetSDBlob(ctx context.Context, sdHash string) (*stream.SDBlob, []byte, error) {
	ret := _mock.Called(ctx, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSDBlob")
	}

	var r0 *stream.SDBlob
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*stream.SDBlob, []byte, error)); ok {
		return returnFunc(ctx, sdHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *stream.SDBlob); ok {
		r0 = returnFunc(ctx, sdHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.SDBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = returnFunc(ctx, sdHash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, sdHash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStreamAcquirer_GetSDBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSDBlob'
type MockStreamAcquirer_GetSDBlob_Call struct {
	*mock.Call
}

// GetSDBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - sdHash string
func (_e *MockStreamAcquirer_Expecter) GetSDBlob(ctx interface{}, sdHash interface{}) *MockStreamAcquirer_GetSDBlob_Call {
	return &MockStreamAcquirer_GetSDBlob_Call{Call: _e.mock.On("GetSDBlob", ctx, sdHash)}
}

func (_c *MockStreamAcquirer_GetSDBlob_Call) Run(run func(ctx context.Context, sdHash string)) *MockStreamAcquirer_GetSDBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamAcquirer_GetSDBlob_Call) Return(sDBlob *stream.SDBlob, bytes []byte, err error) *MockStreamAcquirer_GetSDBlob_Call {
	_c.Call.Return(sDBlob, bytes, err)
	return _c
}

func (_c *MockStreamAcquirer_GetSDBlob_Call) RunAndReturn(run func(ctx context.Context, sdHash string) (*stream.SDBlob, []byte, error)) *MockStreamAcquirer_GetSDBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetStream provides a mock function for the type MockStreamAcquirer
func (_mock *MockStreamAcquirer) GetStream(ctx context.Context, sdHash string, opts ...client.AcquireOption) (client.StreamReader, error) {
	// client.AcquireOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sdHash)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 client.StreamReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.AcquireOption) (client.StreamReader, error)); ok {
		return returnFunc(ctx, sdHash, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.AcquireOption) client.StreamReader); ok {
		r0 = returnFunc(ctx, sdHash, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.StreamReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.AcquireOption) error); ok {
		r1 = returnFunc(ctx, sdHash, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamAcquirer_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type MockStreamAcquirer_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - ctx context.Context
//   - sdHash string
//   - opts ...client.AcquireOption
func (_e *MockStreamAcquirer_Expecter) GetStream(ctx interface{}, sdHash interface{}, opts ...interface{}) *MockStreamAcquirer_GetStream_Call {
	return &MockStreamAcquirer_GetStream_Call{Call: _e.mock.On("GetStream",
		append([]interface{}{ctx, sdHash}, opts...)...)}
}

func (_c *MockStreamAcquirer_GetStream_Call) Run(run func(ctx context.Context, sdHash string, opts ...client.AcquireOption)) *MockStreamAcquirer_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.AcquireOption
		variadicArgs := make([]client.AcquireOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.AcquireOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStreamAcquirer_GetStream_Call) Return(streamReader client.StreamReader, err error) *MockStreamAcquirer_GetStream_Call {
	_c.Call.Return(streamReader, err)
	return _c
}

func (_c *MockStreamAcquirer_GetStream_Call) RunAndReturn(run func(ctx context.Context, sdHash string, opts ...client.AcquireOption) (client.StreamReader, error)) *MockStreamAcquirer_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamResult provides a mock function for the type MockStreamAcquirer
func (_mock *MockStreamAcquirer) GetStreamResult(ctx context.Context, sdHash string, opts ...client.AcquireOption) (*stream.StreamResult, error) {
	// client.AcquireOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sdHash)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamResult")
	}

	var r0 *stream.StreamResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.AcquireOption) (*stream.StreamResult, error)); ok {
		return returnFunc(ctx, sdHash, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.AcquireOption) *stream.StreamResult); ok {
		r0 = returnFunc(ctx, sdHash, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.StreamResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.AcquireOption) error); ok {
		r1 = returnFunc(ctx, sdHash, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamAcquirer_GetStreamResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamResult'
type MockStreamAcquirer_GetStreamResult_Call struct {
	*mock.Call
}

// GetStreamResult is a helper method to define mock.On call
//   - ctx context.Context
//   - sdHash string
//   - opts ...client.AcquireOption
func (_e *MockStreamAcquirer_Expecter) GetStreamResult(ctx interface{}, sdHash interface{}, opts ...interface{}) *MockStreamAcquirer_GetStreamResult_Call {
	return &MockStreamAcquirer_GetStreamResult_Call{Call: _e.mock.On("GetStreamResult",
		append([]interface{}{ctx, sdHash}, opts...)...)}
}

func (_c *MockStreamAcquirer_GetStreamResult_Call) Run(run func(ctx context.Context, sdHash string, opts ...client.AcquireOption)) *MockStreamAcquirer_GetStreamResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.AcquireOption
		variadicArgs := make([]client.AcquireOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.AcquireOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStreamAcquirer_GetStreamResult_Call) Return(streamResult *stream.StreamResult, err error) *MockStreamAcquirer_GetStreamResult_Call {
	_c.Call.Return(streamResult, err)
	return _c
}

func (_c *MockStreamAcquirer_GetStreamResult_Call) RunAndReturn(run func(ctx context.Context, sdHash string, opts ...client.AcquireOption) (*stream.StreamResult, error)) *MockStreamAcquirer_GetStreamResult_Call {
	_c.Call.Return(run)
	return _c
}
