// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/stream"
)

// NewMockStreamReader creates a new instance of MockStreamReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamReader {
	mock := &MockStreamReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamReader is an autogenerated mock type for the StreamReader type
type MockStreamReader struct {
	mock.Mock
}

type MockStreamReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamReader) EXPECT() *MockStreamReader_Expecter {
	return &MockStreamReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStreamReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) Close() *MockStreamReader_Close_Call {
	return &MockStreamReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStreamReader_Close_Call) Run(run func()) *MockStreamReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_Close_Call) Return(err error) *MockStreamReader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamReader_Close_Call) RunAndReturn(run func() error) *MockStreamReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptedSize provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) DecryptedSize() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DecryptedSize")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockStreamReader_DecryptedSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptedSize'
type MockStreamReader_DecryptedSize_Call struct {
	*mock.Call
}

// DecryptedSize is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) DecryptedSize() *MockStreamReader_DecryptedSize_Call {
	return &MockStreamReader_DecryptedSize_Call{Call: _e.mock.On("DecryptedSize")}
}

func (_c *MockStreamReader_DecryptedSize_Call) Run(run func()) *MockStreamReader_DecryptedSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_DecryptedSize_Call) Return(n int64) *MockStreamReader_DecryptedSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStreamReader_DecryptedSize_Call) RunAndReturn(run func() int64) *MockStreamReader_DecryptedSize_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Hash() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStreamReader_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockStreamReader_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) Hash() *MockStreamReader_Hash_Call {
	return &MockStreamReader_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *MockStreamReader_Hash_Call) Run(run func()) *MockStreamReader_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_Hash_Call) Return(s string) *MockStreamReader_Hash_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStreamReader_Hash_Call) RunAndReturn(run func() string) *MockStreamReader_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Progress() float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func() float64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockStreamReader_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockStreamReader_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) Progress() *MockStreamReader_Progress_Call {
	return &MockStreamReader_Progress_Call{Call: _e.mock.On("Progress")}
}

func (_c *MockStreamReader_Progress_Call) Run(run func()) *MockStreamReader_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_Progress_Call) Return(f float64) *MockStreamReader_Progress_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockStreamReader_Progress_Call) RunAndReturn(run func() float64) *MockStreamReader_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockStreamReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockStreamReader_Expecter) Read(p interface{}) *MockStreamReader_Read_Call {
	return &MockStreamReader_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockStreamReader_Read_Call) Run(run func(p []byte)) *MockStreamReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamReader_Read_Call) Return(n int, err error) *MockStreamReader_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStreamReader_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStreamReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// SDBlob provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) SDBlob() *stream.SDBlob {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SDBlob")
	}

	var r0 *stream.SDBlob
	if returnFunc, ok := ret.Get(0).(func() *stream.SDBlob); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.SDBlob)
		}
	}
	return r0
}

// MockStreamReader_SDBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SDBlob'
type MockStreamReader_SDBlob_Call struct {
	*mock.Call
}

// SDBlob is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) SDBlob() *MockStreamReader_SDBlob_Call {
	return &MockStreamReader_SDBlob_Call{Call: _e.mock.On("SDBlob")}
}

func (_c *MockStreamReader_SDBlob_Call) Run(run func()) *MockStreamReader_SDBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_SDBlob_Call) Return(sDBlob *stream.SDBlob) *MockStreamReader_SDBlob_Call {
	_c.Call.Return(sDBlob)
	return _c
}

func (_c *MockStreamReader_SDBlob_Call) RunAndReturn(run func() *stream.SDBlob) *MockStreamReader_SDBlob_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamReader_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockStreamReader_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *MockStreamReader_Expecter) Seek(offset interface{}, whence interface{}) *MockStreamReader_Seek_Call {
	return &MockStreamReader_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *MockStreamReader_Seek_Call) Run(run func(offset int64, whence int)) *MockStreamReader_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamReader_Seek_Call) Return(n int64, err error) *MockStreamReader_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStreamReader_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *MockStreamReader_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockStreamReader
func (_mock *MockStreamReader) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockStreamReader_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockStreamReader_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockStreamReader_Expecter) Size() *MockStreamReader_Size_Call {
	return &MockStreamReader_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockStreamReader_Size_Call) Run(run func()) *MockStreamReader_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamReader_Size_Call) Return(n int64) *MockStreamReader_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStreamReader_Size_Call) RunAndReturn(run func() int64) *MockStreamReader_Size_Call {
	_c.Call.Return(run)
	return _c
}
