template: testify
template-data:
  unroll-variadic: true
filename: "mock_{{.InterfaceName}}.go"
packages:
  go.lumeweb.com/liblbry:
    interfaces:
      AccessControl: {}
      BlobStore: {}
      BlobTransfer: {}
      ReflectorClient: {}
      StoreFactory: {}
  go.lumeweb.com/liblbry/stream:
    interfaces:
      Hasher: {}
      HashIdentifier: {}
      ManifestCreator: {}
      MultihashConverter: {}
      StreamReader: {}
      StreamReaderFactory: {}
      StreamCreator: {}
  go.lumeweb.com/liblbry/protocol:
    interfaces:
      HTTPHandler: {}
      PeerServer: {}