template: testify
template-data:
  unroll-variadic: true
pkgname: "mocks"
filename: "{{.InterfaceName}}.go"
all: true
dir: "{{.InterfaceDir}}/mocks"
packages:
  go.lumeweb.com/liblbry:
  go.lumeweb.com/liblbry/stream:
  go.lumeweb.com/liblbry/protocol:
  go.lumeweb.com/liblbry/protocol/watchdog:
  go.lumeweb.com/liblbry/crypto:
  go.lumeweb.com/liblbry/blob/transfer:
  go.lumeweb.com/liblbry/storage:
  go.lumeweb.com/liblbry/server: