// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobStore creates a new instance of MockBlobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobStore {
	mock := &MockBlobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobStore is an autogenerated mock type for the BlobStore type
type MockBlobStore struct {
	mock.Mock
}

type MockBlobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobStore) EXPECT() *MockBlobStore_Expecter {
	return &MockBlobStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) Get(hash string) ([]byte, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlobStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash string
func (_e *MockBlobStore_Expecter) Get(hash interface{}) *MockBlobStore_Get_Call {
	return &MockBlobStore_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockBlobStore_Get_Call) Run(run func(hash string)) *MockBlobStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlobStore_Get_Call) Return(bytes []byte, err error) *MockBlobStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockBlobStore_Get_Call) RunAndReturn(run func(hash string) ([]byte, error)) *MockBlobStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) Has(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobStore_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockBlobStore_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - hash string
func (_e *MockBlobStore_Expecter) Has(hash interface{}) *MockBlobStore_Has_Call {
	return &MockBlobStore_Has_Call{Call: _e.mock.On("Has", hash)}
}

func (_c *MockBlobStore_Has_Call) Run(run func(hash string)) *MockBlobStore_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlobStore_Has_Call) Return(b bool, err error) *MockBlobStore_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlobStore_Has_Call) RunAndReturn(run func(hash string) (bool, error)) *MockBlobStore_Has_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) List(offset int, limit int) ([]string, error) {
	ret := _mock.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]string, error)); ok {
		return returnFunc(offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []string); ok {
		r0 = returnFunc(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBlobStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockBlobStore_Expecter) List(offset interface{}, limit interface{}) *MockBlobStore_List_Call {
	return &MockBlobStore_List_Call{Call: _e.mock.On("List", offset, limit)}
}

func (_c *MockBlobStore_List_Call) Run(run func(offset int, limit int)) *MockBlobStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobStore_List_Call) Return(strings []string, err error) *MockBlobStore_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockBlobStore_List_Call) RunAndReturn(run func(offset int, limit int) ([]string, error)) *MockBlobStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBlobStore_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockBlobStore_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockBlobStore_Expecter) Name() *MockBlobStore_Name_Call {
	return &MockBlobStore_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockBlobStore_Name_Call) Run(run func()) *MockBlobStore_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlobStore_Name_Call) Return(s string) *MockBlobStore_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBlobStore_Name_Call) RunAndReturn(run func() string) *MockBlobStore_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) Put(hash string, data []byte) error {
	ret := _mock.Called(hash, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBlobStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - hash string
//   - data []byte
func (_e *MockBlobStore_Expecter) Put(hash interface{}, data interface{}) *MockBlobStore_Put_Call {
	return &MockBlobStore_Put_Call{Call: _e.mock.On("Put", hash, data)}
}

func (_c *MockBlobStore_Put_Call) Run(run func(hash string, data []byte)) *MockBlobStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobStore_Put_Call) Return(err error) *MockBlobStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobStore_Put_Call) RunAndReturn(run func(hash string, data []byte) error) *MockBlobStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutSD provides a mock function for the type MockBlobStore
func (_mock *MockBlobStore) PutSD(hash string, data []byte) error {
	ret := _mock.Called(hash, data)

	if len(ret) == 0 {
		panic("no return value specified for PutSD")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobStore_PutSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSD'
type MockBlobStore_PutSD_Call struct {
	*mock.Call
}

// PutSD is a helper method to define mock.On call
//   - hash string
//   - data []byte
func (_e *MockBlobStore_Expecter) PutSD(hash interface{}, data interface{}) *MockBlobStore_PutSD_Call {
	return &MockBlobStore_PutSD_Call{Call: _e.mock.On("PutSD", hash, data)}
}

func (_c *MockBlobStore_PutSD_Call) Run(run func(hash string, data []byte)) *MockBlobStore_PutSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobStore_PutSD_Call) Return(err error) *MockBlobStore_PutSD_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobStore_PutSD_Call) RunAndReturn(run func(hash string, data []byte) error) *MockBlobStore_PutSD_Call {
	_c.Call.Return(run)
	return _c
}
