// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlocklister creates a new instance of MockBlocklister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlocklister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlocklister {
	mock := &MockBlocklister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlocklister is an autogenerated mock type for the Blocklister type
type MockBlocklister struct {
	mock.Mock
}

type MockBlocklister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlocklister) EXPECT() *MockBlocklister_Expecter {
	return &MockBlocklister_Expecter{mock: &_m.Mock}
}

// Wants provides a mock function for the type MockBlocklister
func (_mock *MockBlocklister) Wants(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Wants")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlocklister_Wants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wants'
type MockBlocklister_Wants_Call struct {
	*mock.Call
}

// Wants is a helper method to define mock.On call
//   - hash string
func (_e *MockBlocklister_Expecter) Wants(hash interface{}) *MockBlocklister_Wants_Call {
	return &MockBlocklister_Wants_Call{Call: _e.mock.On("Wants", hash)}
}

func (_c *MockBlocklister_Wants_Call) Run(run func(hash string)) *MockBlocklister_Wants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlocklister_Wants_Call) Return(b bool, err error) *MockBlocklister_Wants_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlocklister_Wants_Call) RunAndReturn(run func(hash string) (bool, error)) *MockBlocklister_Wants_Call {
	_c.Call.Return(run)
	return _c
}
