// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDummyBlocklistBlobStore creates a new instance of MockDummyBlocklistBlobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDummyBlocklistBlobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDummyBlocklistBlobStore {
	mock := &MockDummyBlocklistBlobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDummyBlocklistBlobStore is an autogenerated mock type for the DummyBlocklistBlobStore type
type MockDummyBlocklistBlobStore struct {
	mock.Mock
}

type MockDummyBlocklistBlobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDummyBlocklistBlobStore) EXPECT() *MockDummyBlocklistBlobStore_Expecter {
	return &MockDummyBlocklistBlobStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Delete(hash string) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyBlocklistBlobStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDummyBlocklistBlobStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - hash string
func (_e *MockDummyBlocklistBlobStore_Expecter) Delete(hash interface{}) *MockDummyBlocklistBlobStore_Delete_Call {
	return &MockDummyBlocklistBlobStore_Delete_Call{Call: _e.mock.On("Delete", hash)}
}

func (_c *MockDummyBlocklistBlobStore_Delete_Call) Run(run func(hash string)) *MockDummyBlocklistBlobStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Delete_Call) Return(err error) *MockDummyBlocklistBlobStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Delete_Call) RunAndReturn(run func(hash string) error) *MockDummyBlocklistBlobStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Get(hash string) ([]byte, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyBlocklistBlobStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDummyBlocklistBlobStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash string
func (_e *MockDummyBlocklistBlobStore_Expecter) Get(hash interface{}) *MockDummyBlocklistBlobStore_Get_Call {
	return &MockDummyBlocklistBlobStore_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockDummyBlocklistBlobStore_Get_Call) Run(run func(hash string)) *MockDummyBlocklistBlobStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Get_Call) Return(bytes []byte, err error) *MockDummyBlocklistBlobStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Get_Call) RunAndReturn(run func(hash string) ([]byte, error)) *MockDummyBlocklistBlobStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Has(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyBlocklistBlobStore_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockDummyBlocklistBlobStore_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - hash string
func (_e *MockDummyBlocklistBlobStore_Expecter) Has(hash interface{}) *MockDummyBlocklistBlobStore_Has_Call {
	return &MockDummyBlocklistBlobStore_Has_Call{Call: _e.mock.On("Has", hash)}
}

func (_c *MockDummyBlocklistBlobStore_Has_Call) Run(run func(hash string)) *MockDummyBlocklistBlobStore_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Has_Call) Return(b bool, err error) *MockDummyBlocklistBlobStore_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Has_Call) RunAndReturn(run func(hash string) (bool, error)) *MockDummyBlocklistBlobStore_Has_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) List(offset int, limit int) ([]string, error) {
	ret := _mock.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]string, error)); ok {
		return returnFunc(offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []string); ok {
		r0 = returnFunc(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyBlocklistBlobStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDummyBlocklistBlobStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - offset int
//   - limit int
func (_e *MockDummyBlocklistBlobStore_Expecter) List(offset interface{}, limit interface{}) *MockDummyBlocklistBlobStore_List_Call {
	return &MockDummyBlocklistBlobStore_List_Call{Call: _e.mock.On("List", offset, limit)}
}

func (_c *MockDummyBlocklistBlobStore_List_Call) Run(run func(offset int, limit int)) *MockDummyBlocklistBlobStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_List_Call) Return(strings []string, err error) *MockDummyBlocklistBlobStore_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_List_Call) RunAndReturn(run func(offset int, limit int) ([]string, error)) *MockDummyBlocklistBlobStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDummyBlocklistBlobStore_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDummyBlocklistBlobStore_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDummyBlocklistBlobStore_Expecter) Name() *MockDummyBlocklistBlobStore_Name_Call {
	return &MockDummyBlocklistBlobStore_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDummyBlocklistBlobStore_Name_Call) Run(run func()) *MockDummyBlocklistBlobStore_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Name_Call) Return(s string) *MockDummyBlocklistBlobStore_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Name_Call) RunAndReturn(run func() string) *MockDummyBlocklistBlobStore_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Put(hash string, data []byte) error {
	ret := _mock.Called(hash, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyBlocklistBlobStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockDummyBlocklistBlobStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - hash string
//   - data []byte
func (_e *MockDummyBlocklistBlobStore_Expecter) Put(hash interface{}, data interface{}) *MockDummyBlocklistBlobStore_Put_Call {
	return &MockDummyBlocklistBlobStore_Put_Call{Call: _e.mock.On("Put", hash, data)}
}

func (_c *MockDummyBlocklistBlobStore_Put_Call) Run(run func(hash string, data []byte)) *MockDummyBlocklistBlobStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Put_Call) Return(err error) *MockDummyBlocklistBlobStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Put_Call) RunAndReturn(run func(hash string, data []byte) error) *MockDummyBlocklistBlobStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutSD provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) PutSD(hash string, data []byte) error {
	ret := _mock.Called(hash, data)

	if len(ret) == 0 {
		panic("no return value specified for PutSD")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyBlocklistBlobStore_PutSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSD'
type MockDummyBlocklistBlobStore_PutSD_Call struct {
	*mock.Call
}

// PutSD is a helper method to define mock.On call
//   - hash string
//   - data []byte
func (_e *MockDummyBlocklistBlobStore_Expecter) PutSD(hash interface{}, data interface{}) *MockDummyBlocklistBlobStore_PutSD_Call {
	return &MockDummyBlocklistBlobStore_PutSD_Call{Call: _e.mock.On("PutSD", hash, data)}
}

func (_c *MockDummyBlocklistBlobStore_PutSD_Call) Run(run func(hash string, data []byte)) *MockDummyBlocklistBlobStore_PutSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_PutSD_Call) Return(err error) *MockDummyBlocklistBlobStore_PutSD_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_PutSD_Call) RunAndReturn(run func(hash string, data []byte) error) *MockDummyBlocklistBlobStore_PutSD_Call {
	_c.Call.Return(run)
	return _c
}

// Wants provides a mock function for the type MockDummyBlocklistBlobStore
func (_mock *MockDummyBlocklistBlobStore) Wants(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Wants")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyBlocklistBlobStore_Wants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wants'
type MockDummyBlocklistBlobStore_Wants_Call struct {
	*mock.Call
}

// Wants is a helper method to define mock.On call
//   - hash string
func (_e *MockDummyBlocklistBlobStore_Expecter) Wants(hash interface{}) *MockDummyBlocklistBlobStore_Wants_Call {
	return &MockDummyBlocklistBlobStore_Wants_Call{Call: _e.mock.On("Wants", hash)}
}

func (_c *MockDummyBlocklistBlobStore_Wants_Call) Run(run func(hash string)) *MockDummyBlocklistBlobStore_Wants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Wants_Call) Return(b bool, err error) *MockDummyBlocklistBlobStore_Wants_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDummyBlocklistBlobStore_Wants_Call) RunAndReturn(run func(hash string) (bool, error)) *MockDummyBlocklistBlobStore_Wants_Call {
	_c.Call.Return(run)
	return _c
}
