// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDummyMissingBlobStore creates a new instance of MockDummyMissingBlobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDummyMissingBlobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDummyMissingBlobStore {
	mock := &MockDummyMissingBlobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDummyMissingBlobStore is an autogenerated mock type for the DummyMissingBlobStore type
type MockDummyMissingBlobStore struct {
	mock.Mock
}

type MockDummyMissingBlobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDummyMissingBlobStore) EXPECT() *MockDummyMissingBlobStore_Expecter {
	return &MockDummyMissingBlobStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) Delete(ctx context.Context, hash string) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyMissingBlobStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDummyMissingBlobStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockDummyMissingBlobStore_Expecter) Delete(ctx interface{}, hash interface{}) *MockDummyMissingBlobStore_Delete_Call {
	return &MockDummyMissingBlobStore_Delete_Call{Call: _e.mock.On("Delete", ctx, hash)}
}

func (_c *MockDummyMissingBlobStore_Delete_Call) Run(run func(ctx context.Context, hash string)) *MockDummyMissingBlobStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_Delete_Call) Return(err error) *MockDummyMissingBlobStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyMissingBlobStore_Delete_Call) RunAndReturn(run func(ctx context.Context, hash string) error) *MockDummyMissingBlobStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) Get(ctx context.Context, hash string) ([]byte, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyMissingBlobStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDummyMissingBlobStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockDummyMissingBlobStore_Expecter) Get(ctx interface{}, hash interface{}) *MockDummyMissingBlobStore_Get_Call {
	return &MockDummyMissingBlobStore_Get_Call{Call: _e.mock.On("Get", ctx, hash)}
}

func (_c *MockDummyMissingBlobStore_Get_Call) Run(run func(ctx context.Context, hash string)) *MockDummyMissingBlobStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_Get_Call) Return(bytes []byte, err error) *MockDummyMissingBlobStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDummyMissingBlobStore_Get_Call) RunAndReturn(run func(ctx context.Context, hash string) ([]byte, error)) *MockDummyMissingBlobStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) Has(ctx context.Context, hash string) (bool, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyMissingBlobStore_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockDummyMissingBlobStore_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockDummyMissingBlobStore_Expecter) Has(ctx interface{}, hash interface{}) *MockDummyMissingBlobStore_Has_Call {
	return &MockDummyMissingBlobStore_Has_Call{Call: _e.mock.On("Has", ctx, hash)}
}

func (_c *MockDummyMissingBlobStore_Has_Call) Run(run func(ctx context.Context, hash string)) *MockDummyMissingBlobStore_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_Has_Call) Return(b bool, err error) *MockDummyMissingBlobStore_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDummyMissingBlobStore_Has_Call) RunAndReturn(run func(ctx context.Context, hash string) (bool, error)) *MockDummyMissingBlobStore_Has_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) List(ctx context.Context, offset int, limit int) ([]string, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]string, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []string); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyMissingBlobStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDummyMissingBlobStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockDummyMissingBlobStore_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockDummyMissingBlobStore_List_Call {
	return &MockDummyMissingBlobStore_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockDummyMissingBlobStore_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockDummyMissingBlobStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_List_Call) Return(strings []string, err error) *MockDummyMissingBlobStore_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDummyMissingBlobStore_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]string, error)) *MockDummyMissingBlobStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// MissingBlobsForKnownStream provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) MissingBlobsForKnownStream(streamHash string) ([]string, error) {
	ret := _mock.Called(streamHash)

	if len(ret) == 0 {
		panic("no return value specified for MissingBlobsForKnownStream")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(streamHash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(streamHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(streamHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MissingBlobsForKnownStream'
type MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call struct {
	*mock.Call
}

// MissingBlobsForKnownStream is a helper method to define mock.On call
//   - streamHash string
func (_e *MockDummyMissingBlobStore_Expecter) MissingBlobsForKnownStream(streamHash interface{}) *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call {
	return &MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call{Call: _e.mock.On("MissingBlobsForKnownStream", streamHash)}
}

func (_c *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call) Run(run func(streamHash string)) *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call) Return(strings []string, err error) *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call) RunAndReturn(run func(streamHash string) ([]string, error)) *MockDummyMissingBlobStore_MissingBlobsForKnownStream_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDummyMissingBlobStore_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDummyMissingBlobStore_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDummyMissingBlobStore_Expecter) Name() *MockDummyMissingBlobStore_Name_Call {
	return &MockDummyMissingBlobStore_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDummyMissingBlobStore_Name_Call) Run(run func()) *MockDummyMissingBlobStore_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_Name_Call) Return(s string) *MockDummyMissingBlobStore_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDummyMissingBlobStore_Name_Call) RunAndReturn(run func() string) *MockDummyMissingBlobStore_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) Put(ctx context.Context, hash string, data []byte) error {
	ret := _mock.Called(ctx, hash, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyMissingBlobStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockDummyMissingBlobStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - data []byte
func (_e *MockDummyMissingBlobStore_Expecter) Put(ctx interface{}, hash interface{}, data interface{}) *MockDummyMissingBlobStore_Put_Call {
	return &MockDummyMissingBlobStore_Put_Call{Call: _e.mock.On("Put", ctx, hash, data)}
}

func (_c *MockDummyMissingBlobStore_Put_Call) Run(run func(ctx context.Context, hash string, data []byte)) *MockDummyMissingBlobStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_Put_Call) Return(err error) *MockDummyMissingBlobStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyMissingBlobStore_Put_Call) RunAndReturn(run func(ctx context.Context, hash string, data []byte) error) *MockDummyMissingBlobStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutSD provides a mock function for the type MockDummyMissingBlobStore
func (_mock *MockDummyMissingBlobStore) PutSD(ctx context.Context, hash string, data []byte) error {
	ret := _mock.Called(ctx, hash, data)

	if len(ret) == 0 {
		panic("no return value specified for PutSD")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDummyMissingBlobStore_PutSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSD'
type MockDummyMissingBlobStore_PutSD_Call struct {
	*mock.Call
}

// PutSD is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - data []byte
func (_e *MockDummyMissingBlobStore_Expecter) PutSD(ctx interface{}, hash interface{}, data interface{}) *MockDummyMissingBlobStore_PutSD_Call {
	return &MockDummyMissingBlobStore_PutSD_Call{Call: _e.mock.On("PutSD", ctx, hash, data)}
}

func (_c *MockDummyMissingBlobStore_PutSD_Call) Run(run func(ctx context.Context, hash string, data []byte)) *MockDummyMissingBlobStore_PutSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDummyMissingBlobStore_PutSD_Call) Return(err error) *MockDummyMissingBlobStore_PutSD_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDummyMissingBlobStore_PutSD_Call) RunAndReturn(run func(ctx context.Context, hash string, data []byte) error) *MockDummyMissingBlobStore_PutSD_Call {
	_c.Call.Return(run)
	return _c
}
