// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNeededBlobChecker creates a new instance of MockNeededBlobChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNeededBlobChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNeededBlobChecker {
	mock := &MockNeededBlobChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNeededBlobChecker is an autogenerated mock type for the NeededBlobChecker type
type MockNeededBlobChecker struct {
	mock.Mock
}

type MockNeededBlobChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNeededBlobChecker) EXPECT() *MockNeededBlobChecker_Expecter {
	return &MockNeededBlobChecker_Expecter{mock: &_m.Mock}
}

// MissingBlobsForKnownStream provides a mock function for the type MockNeededBlobChecker
func (_mock *MockNeededBlobChecker) MissingBlobsForKnownStream(streamHash string) ([]string, error) {
	ret := _mock.Called(streamHash)

	if len(ret) == 0 {
		panic("no return value specified for MissingBlobsForKnownStream")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(streamHash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(streamHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(streamHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNeededBlobChecker_MissingBlobsForKnownStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MissingBlobsForKnownStream'
type MockNeededBlobChecker_MissingBlobsForKnownStream_Call struct {
	*mock.Call
}

// MissingBlobsForKnownStream is a helper method to define mock.On call
//   - streamHash string
func (_e *MockNeededBlobChecker_Expecter) MissingBlobsForKnownStream(streamHash interface{}) *MockNeededBlobChecker_MissingBlobsForKnownStream_Call {
	return &MockNeededBlobChecker_MissingBlobsForKnownStream_Call{Call: _e.mock.On("MissingBlobsForKnownStream", streamHash)}
}

func (_c *MockNeededBlobChecker_MissingBlobsForKnownStream_Call) Run(run func(streamHash string)) *MockNeededBlobChecker_MissingBlobsForKnownStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNeededBlobChecker_MissingBlobsForKnownStream_Call) Return(strings []string, err error) *MockNeededBlobChecker_MissingBlobsForKnownStream_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockNeededBlobChecker_MissingBlobsForKnownStream_Call) RunAndReturn(run func(streamHash string) ([]string, error)) *MockNeededBlobChecker_MissingBlobsForKnownStream_Call {
	_c.Call.Return(run)
	return _c
}
