package wallet

import (
	"encoding/hex"
	"fmt"

	"github.com/lbryio/lbcd/btcec"
)

// TestMnemonic is a valid Electrum/LBRY mnemonic for use in tests.
// Generated by MakeSeed(). Never use with real funds.
const TestMnemonic = "will bus cluster trumpet jump venue truly habit decrease stuff renew horse"

// Wallet represents an HD wallet derived from an Electrum mnemonic.
// All operations are pure data/key derivation — no I/O.
type Wallet struct {
	mnemonic  string
	seed      []byte
	masterKey *ExtendedKey
	privKey   *btcec.PrivateKey
	pubKey    *btcec.PublicKey
	address   *Address
}

// NewFromMnemonic creates a Wallet from an Electrum/LBRY mnemonic phrase.
// Validates using the Electrum seed checksum (HMAC-SHA512 "Seed version" prefix),
// not BIP39 checksum.
func NewFromMnemonic(mnemonicStr string) (*Wallet, error) {
	if !IsValid(mnemonicStr) {
		return nil, fmt.Errorf("invalid mnemonic: failed Electrum seed checksum or unknown words")
	}
	seed := MnemonicToSeed(mnemonicStr, Passphrase)
	return newFromSeed(seed, mnemonicStr)
}

// NewFromSeed creates a Wallet from raw seed bytes.
// The seed should be 64 bytes (from PBKDF2). No mnemonic validation is performed.
func NewFromSeed(seed []byte) (*Wallet, error) {
	return newFromSeed(seed, "")
}

func newFromSeed(seed []byte, mnemonicStr string) (*Wallet, error) {
	masterKey, err := NewMaster(seed)
	if err != nil {
		return nil, fmt.Errorf("derive master key: %w", err)
	}

	w := &Wallet{
		mnemonic:  mnemonicStr,
		seed:      seed,
		masterKey: masterKey,
	}

	if err := w.deriveAccount0(); err != nil {
		return nil, err
	}

	return w, nil
}

// deriveAccount0 derives m/0/0 (non-hardened) and caches the key material.
// LBRY does NOT use BIP44 — it uses simple 2-level BIP32 derivation:
// receiving addresses are m/0/N, change are m/1/N, channel keys are m/2/N.
func (w *Wallet) deriveAccount0() error {
	// m/0
	receiving, err := w.masterKey.Derive(0)
	if err != nil {
		return fmt.Errorf("derive receiving chain: %w", err)
	}

	// m/0/0
	child, err := receiving.Derive(0)
	if err != nil {
		return fmt.Errorf("derive child: %w", err)
	}

	privKey, err := child.ECPrivKey()
	if err != nil {
		return fmt.Errorf("get private key: %w", err)
	}

	w.privKey = privKey
	w.pubKey = privKey.PubKey()
	w.address = AddressFromPubKey(w.pubKey)

	return nil
}

// DeriveKey derives a child key at the given chain and index.
// LBRY path: m/chain/index (non-hardened).
// chain: 0=receiving, 1=change, 2=channel.
func (w *Wallet) DeriveKey(chain, index uint32) (*ExtendedKey, error) {
	chainKey, err := w.masterKey.Derive(chain)
	if err != nil {
		return nil, fmt.Errorf("derive chain: %w", err)
	}
	return chainKey.Derive(index)
}

// Address returns the P2PKH address for this wallet (m/0/0).
func (w *Wallet) Address() *Address { return w.address }

// AddressString returns the encoded P2PKH address string.
func (w *Wallet) AddressString() string { return w.address.EncodeAddress() }

// AddressAt returns the P2PKH address at m/chain/index.
func (w *Wallet) AddressAt(chain, index uint32) (*Address, error) {
	child, err := w.DeriveKey(chain, index)
	if err != nil {
		return nil, err
	}
	priv, err := child.ECPrivKey()
	if err != nil {
		return nil, err
	}
	return AddressFromPrivKey(priv), nil
}

// AddressStringAt returns the encoded P2PKH address at m/chain/index.
func (w *Wallet) AddressStringAt(chain, index uint32) (string, error) {
	addr, err := w.AddressAt(chain, index)
	if err != nil {
		return "", err
	}
	return addr.EncodeAddress(), nil
}

// PubKeyScriptAt returns the P2PKH scriptPubKey for the address at m/chain/index.
func (w *Wallet) PubKeyScriptAt(chain, index uint32) ([]byte, error) {
	addr, err := w.AddressAt(chain, index)
	if err != nil {
		return nil, err
	}
	return addr.PubKeyScript(), nil
}

// PrivateKeyAt returns the private key at m/chain/index.
func (w *Wallet) PrivateKeyAt(chain, index uint32) (*btcec.PrivateKey, error) {
	child, err := w.DeriveKey(chain, index)
	if err != nil {
		return nil, err
	}
	return child.ECPrivKey()
}

// PrivateKey returns the private key at m/0/0.
func (w *Wallet) PrivateKey() *btcec.PrivateKey { return w.privKey }

// PrivateKeyHex returns the private key at m/0/0 as a hex string.
func (w *Wallet) PrivateKeyHex() string {
	return hex.EncodeToString(w.privKey.Serialize())
}

// PublicKey returns the compressed public key at m/0/0.
func (w *Wallet) PublicKey() *btcec.PublicKey { return w.pubKey }

// PublicKeyHex returns the compressed public key as a hex string.
func (w *Wallet) PublicKeyHex() string {
	return hex.EncodeToString(w.pubKey.SerializeCompressed())
}

// Mnemonic returns the original mnemonic phrase.
func (w *Wallet) Mnemonic() string { return w.mnemonic }

// Seed returns the raw seed bytes.
func (w *Wallet) Seed() []byte { return w.seed }

// MasterKey returns the BIP32 master extended key.
func (w *Wallet) MasterKey() *ExtendedKey { return w.masterKey }
