// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
)

// NewMockCompletionHandler creates a new instance of MockCompletionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompletionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompletionHandler {
	mock := &MockCompletionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompletionHandler is an autogenerated mock type for the CompletionHandler type
type MockCompletionHandler struct {
	mock.Mock
}

type MockCompletionHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompletionHandler) EXPECT() *MockCompletionHandler_Expecter {
	return &MockCompletionHandler_Expecter{mock: &_m.Mock}
}

// CompleteWithData provides a mock function for the type MockCompletionHandler
func (_mock *MockCompletionHandler) CompleteWithData(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string) {
	_mock.Called(req, data, raceCancel, hash)
	return
}

// MockCompletionHandler_CompleteWithData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithData'
type MockCompletionHandler_CompleteWithData_Call struct {
	*mock.Call
}

// CompleteWithData is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - data []byte
//   - raceCancel context.CancelFunc
//   - hash string
func (_e *MockCompletionHandler_Expecter) CompleteWithData(req interface{}, data interface{}, raceCancel interface{}, hash interface{}) *MockCompletionHandler_CompleteWithData_Call {
	return &MockCompletionHandler_CompleteWithData_Call{Call: _e.mock.On("CompleteWithData", req, data, raceCancel, hash)}
}

func (_c *MockCompletionHandler_CompleteWithData_Call) Run(run func(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string)) *MockCompletionHandler_CompleteWithData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 context.CancelFunc
		if args[2] != nil {
			arg2 = args[2].(context.CancelFunc)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCompletionHandler_CompleteWithData_Call) Return() *MockCompletionHandler_CompleteWithData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCompletionHandler_CompleteWithData_Call) RunAndReturn(run func(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string)) *MockCompletionHandler_CompleteWithData_Call {
	_c.Run(run)
	return _c
}

// CompleteWithError provides a mock function for the type MockCompletionHandler
func (_mock *MockCompletionHandler) CompleteWithError(req *blob.BlobRequest, err error) error {
	ret := _mock.Called(req, err)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWithError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) error); ok {
		r0 = returnFunc(req, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompletionHandler_CompleteWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithError'
type MockCompletionHandler_CompleteWithError_Call struct {
	*mock.Call
}

// CompleteWithError is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
func (_e *MockCompletionHandler_Expecter) CompleteWithError(req interface{}, err interface{}) *MockCompletionHandler_CompleteWithError_Call {
	return &MockCompletionHandler_CompleteWithError_Call{Call: _e.mock.On("CompleteWithError", req, err)}
}

func (_c *MockCompletionHandler_CompleteWithError_Call) Run(run func(req *blob.BlobRequest, err error)) *MockCompletionHandler_CompleteWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompletionHandler_CompleteWithError_Call) Return(err1 error) *MockCompletionHandler_CompleteWithError_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockCompletionHandler_CompleteWithError_Call) RunAndReturn(run func(req *blob.BlobRequest, err error) error) *MockCompletionHandler_CompleteWithError_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWithErrorAndCancel provides a mock function for the type MockCompletionHandler
func (_mock *MockCompletionHandler) CompleteWithErrorAndCancel(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string) {
	_mock.Called(req, err, raceCancel, hash)
	return
}

// MockCompletionHandler_CompleteWithErrorAndCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithErrorAndCancel'
type MockCompletionHandler_CompleteWithErrorAndCancel_Call struct {
	*mock.Call
}

// CompleteWithErrorAndCancel is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
//   - raceCancel context.CancelFunc
//   - hash string
func (_e *MockCompletionHandler_Expecter) CompleteWithErrorAndCancel(req interface{}, err interface{}, raceCancel interface{}, hash interface{}) *MockCompletionHandler_CompleteWithErrorAndCancel_Call {
	return &MockCompletionHandler_CompleteWithErrorAndCancel_Call{Call: _e.mock.On("CompleteWithErrorAndCancel", req, err, raceCancel, hash)}
}

func (_c *MockCompletionHandler_CompleteWithErrorAndCancel_Call) Run(run func(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string)) *MockCompletionHandler_CompleteWithErrorAndCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 context.CancelFunc
		if args[2] != nil {
			arg2 = args[2].(context.CancelFunc)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCompletionHandler_CompleteWithErrorAndCancel_Call) Return() *MockCompletionHandler_CompleteWithErrorAndCancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCompletionHandler_CompleteWithErrorAndCancel_Call) RunAndReturn(run func(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string)) *MockCompletionHandler_CompleteWithErrorAndCancel_Call {
	_c.Run(run)
	return _c
}

// TrackFailedPeer provides a mock function for the type MockCompletionHandler
func (_mock *MockCompletionHandler) TrackFailedPeer(req *blob.BlobRequest, err error) (int32, bool) {
	ret := _mock.Called(req, err)

	if len(ret) == 0 {
		panic("no return value specified for TrackFailedPeer")
	}

	var r0 int32
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) (int32, bool)); ok {
		return returnFunc(req, err)
	}
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) int32); ok {
		r0 = returnFunc(req, err)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(*blob.BlobRequest, error) bool); ok {
		r1 = returnFunc(req, err)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCompletionHandler_TrackFailedPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackFailedPeer'
type MockCompletionHandler_TrackFailedPeer_Call struct {
	*mock.Call
}

// TrackFailedPeer is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
func (_e *MockCompletionHandler_Expecter) TrackFailedPeer(req interface{}, err interface{}) *MockCompletionHandler_TrackFailedPeer_Call {
	return &MockCompletionHandler_TrackFailedPeer_Call{Call: _e.mock.On("TrackFailedPeer", req, err)}
}

func (_c *MockCompletionHandler_TrackFailedPeer_Call) Run(run func(req *blob.BlobRequest, err error)) *MockCompletionHandler_TrackFailedPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompletionHandler_TrackFailedPeer_Call) Return(n int32, b bool) *MockCompletionHandler_TrackFailedPeer_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *MockCompletionHandler_TrackFailedPeer_Call) RunAndReturn(run func(req *blob.BlobRequest, err error) (int32, bool)) *MockCompletionHandler_TrackFailedPeer_Call {
	_c.Call.Return(run)
	return _c
}
