// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht"
	"go.lumeweb.com/lbry-dht/bits"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
)

// NewMockPeerTaskExecutor creates a new instance of MockPeerTaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerTaskExecutor {
	mock := &MockPeerTaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerTaskExecutor is an autogenerated mock type for the PeerTaskExecutor type
type MockPeerTaskExecutor struct {
	mock.Mock
}

type MockPeerTaskExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerTaskExecutor) EXPECT() *MockPeerTaskExecutor_Expecter {
	return &MockPeerTaskExecutor_Expecter{mock: &_m.Mock}
}

// ExecutePeerTasks provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) ExecutePeerTasks(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest) error {
	ret := _mock.Called(ctx, hash, contacts, hashBitmap, req)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePeerTasks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []dht.Contact, bits.Bitmap, *blob.BlobRequest) error); ok {
		r0 = returnFunc(ctx, hash, contacts, hashBitmap, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerTaskExecutor_ExecutePeerTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutePeerTasks'
type MockPeerTaskExecutor_ExecutePeerTasks_Call struct {
	*mock.Call
}

// ExecutePeerTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - contacts []dht.Contact
//   - hashBitmap bits.Bitmap
//   - req *blob.BlobRequest
func (_e *MockPeerTaskExecutor_Expecter) ExecutePeerTasks(ctx interface{}, hash interface{}, contacts interface{}, hashBitmap interface{}, req interface{}) *MockPeerTaskExecutor_ExecutePeerTasks_Call {
	return &MockPeerTaskExecutor_ExecutePeerTasks_Call{Call: _e.mock.On("ExecutePeerTasks", ctx, hash, contacts, hashBitmap, req)}
}

func (_c *MockPeerTaskExecutor_ExecutePeerTasks_Call) Run(run func(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest)) *MockPeerTaskExecutor_ExecutePeerTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []dht.Contact
		if args[2] != nil {
			arg2 = args[2].([]dht.Contact)
		}
		var arg3 bits.Bitmap
		if args[3] != nil {
			arg3 = args[3].(bits.Bitmap)
		}
		var arg4 *blob.BlobRequest
		if args[4] != nil {
			arg4 = args[4].(*blob.BlobRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPeerTaskExecutor_ExecutePeerTasks_Call) Return(err error) *MockPeerTaskExecutor_ExecutePeerTasks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerTaskExecutor_ExecutePeerTasks_Call) RunAndReturn(run func(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest) error) *MockPeerTaskExecutor_ExecutePeerTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxConcurrency provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) GetMaxConcurrency() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxConcurrency")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPeerTaskExecutor_GetMaxConcurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxConcurrency'
type MockPeerTaskExecutor_GetMaxConcurrency_Call struct {
	*mock.Call
}

// GetMaxConcurrency is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) GetMaxConcurrency() *MockPeerTaskExecutor_GetMaxConcurrency_Call {
	return &MockPeerTaskExecutor_GetMaxConcurrency_Call{Call: _e.mock.On("GetMaxConcurrency")}
}

func (_c *MockPeerTaskExecutor_GetMaxConcurrency_Call) Run(run func()) *MockPeerTaskExecutor_GetMaxConcurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_GetMaxConcurrency_Call) Return(n int) *MockPeerTaskExecutor_GetMaxConcurrency_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPeerTaskExecutor_GetMaxConcurrency_Call) RunAndReturn(run func() int) *MockPeerTaskExecutor_GetMaxConcurrency_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskStats provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) GetTaskStats() (int64, int64, int64) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStats")
	}

	var r0 int64
	var r1 int64
	var r2 int64
	if returnFunc, ok := ret.Get(0).(func() (int64, int64, int64)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() int64); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func() int64); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(int64)
	}
	return r0, r1, r2
}

// MockPeerTaskExecutor_GetTaskStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskStats'
type MockPeerTaskExecutor_GetTaskStats_Call struct {
	*mock.Call
}

// GetTaskStats is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) GetTaskStats() *MockPeerTaskExecutor_GetTaskStats_Call {
	return &MockPeerTaskExecutor_GetTaskStats_Call{Call: _e.mock.On("GetTaskStats")}
}

func (_c *MockPeerTaskExecutor_GetTaskStats_Call) Run(run func()) *MockPeerTaskExecutor_GetTaskStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_GetTaskStats_Call) Return(submitted int64, completed int64, pending int64) *MockPeerTaskExecutor_GetTaskStats_Call {
	_c.Call.Return(submitted, completed, pending)
	return _c
}

func (_c *MockPeerTaskExecutor_GetTaskStats_Call) RunAndReturn(run func() (int64, int64, int64)) *MockPeerTaskExecutor_GetTaskStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkerPoolStats provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) GetWorkerPoolStats() (int, int, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWorkerPoolStats")
	}

	var r0 int
	var r1 int
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func() (int, int, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() int); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func() bool); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockPeerTaskExecutor_GetWorkerPoolStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkerPoolStats'
type MockPeerTaskExecutor_GetWorkerPoolStats_Call struct {
	*mock.Call
}

// GetWorkerPoolStats is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) GetWorkerPoolStats() *MockPeerTaskExecutor_GetWorkerPoolStats_Call {
	return &MockPeerTaskExecutor_GetWorkerPoolStats_Call{Call: _e.mock.On("GetWorkerPoolStats")}
}

func (_c *MockPeerTaskExecutor_GetWorkerPoolStats_Call) Run(run func()) *MockPeerTaskExecutor_GetWorkerPoolStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_GetWorkerPoolStats_Call) Return(size int, waitingQueueSize int, stopped bool) *MockPeerTaskExecutor_GetWorkerPoolStats_Call {
	_c.Call.Return(size, waitingQueueSize, stopped)
	return _c
}

func (_c *MockPeerTaskExecutor_GetWorkerPoolStats_Call) RunAndReturn(run func() (int, int, bool)) *MockPeerTaskExecutor_GetWorkerPoolStats_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerTaskExecutor_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockPeerTaskExecutor_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) IsStopped() *MockPeerTaskExecutor_IsStopped_Call {
	return &MockPeerTaskExecutor_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockPeerTaskExecutor_IsStopped_Call) Run(run func()) *MockPeerTaskExecutor_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_IsStopped_Call) Return(b bool) *MockPeerTaskExecutor_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerTaskExecutor_IsStopped_Call) RunAndReturn(run func() bool) *MockPeerTaskExecutor_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// SetMaxConcurrency provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) SetMaxConcurrency(maxConcurrency int) {
	_mock.Called(maxConcurrency)
	return
}

// MockPeerTaskExecutor_SetMaxConcurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxConcurrency'
type MockPeerTaskExecutor_SetMaxConcurrency_Call struct {
	*mock.Call
}

// SetMaxConcurrency is a helper method to define mock.On call
//   - maxConcurrency int
func (_e *MockPeerTaskExecutor_Expecter) SetMaxConcurrency(maxConcurrency interface{}) *MockPeerTaskExecutor_SetMaxConcurrency_Call {
	return &MockPeerTaskExecutor_SetMaxConcurrency_Call{Call: _e.mock.On("SetMaxConcurrency", maxConcurrency)}
}

func (_c *MockPeerTaskExecutor_SetMaxConcurrency_Call) Run(run func(maxConcurrency int)) *MockPeerTaskExecutor_SetMaxConcurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerTaskExecutor_SetMaxConcurrency_Call) Return() *MockPeerTaskExecutor_SetMaxConcurrency_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerTaskExecutor_SetMaxConcurrency_Call) RunAndReturn(run func(maxConcurrency int)) *MockPeerTaskExecutor_SetMaxConcurrency_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) Start() {
	_mock.Called()
	return
}

// MockPeerTaskExecutor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPeerTaskExecutor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) Start() *MockPeerTaskExecutor_Start_Call {
	return &MockPeerTaskExecutor_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPeerTaskExecutor_Start_Call) Run(run func()) *MockPeerTaskExecutor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_Start_Call) Return() *MockPeerTaskExecutor_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerTaskExecutor_Start_Call) RunAndReturn(run func()) *MockPeerTaskExecutor_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) Stop() {
	_mock.Called()
	return
}

// MockPeerTaskExecutor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPeerTaskExecutor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) Stop() *MockPeerTaskExecutor_Stop_Call {
	return &MockPeerTaskExecutor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPeerTaskExecutor_Stop_Call) Run(run func()) *MockPeerTaskExecutor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_Stop_Call) Return() *MockPeerTaskExecutor_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerTaskExecutor_Stop_Call) RunAndReturn(run func()) *MockPeerTaskExecutor_Stop_Call {
	_c.Run(run)
	return _c
}

// WaitAllTasksComplete provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) WaitAllTasksComplete() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitAllTasksComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerTaskExecutor_WaitAllTasksComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitAllTasksComplete'
type MockPeerTaskExecutor_WaitAllTasksComplete_Call struct {
	*mock.Call
}

// WaitAllTasksComplete is a helper method to define mock.On call
func (_e *MockPeerTaskExecutor_Expecter) WaitAllTasksComplete() *MockPeerTaskExecutor_WaitAllTasksComplete_Call {
	return &MockPeerTaskExecutor_WaitAllTasksComplete_Call{Call: _e.mock.On("WaitAllTasksComplete")}
}

func (_c *MockPeerTaskExecutor_WaitAllTasksComplete_Call) Run(run func()) *MockPeerTaskExecutor_WaitAllTasksComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTaskExecutor_WaitAllTasksComplete_Call) Return(err error) *MockPeerTaskExecutor_WaitAllTasksComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerTaskExecutor_WaitAllTasksComplete_Call) RunAndReturn(run func() error) *MockPeerTaskExecutor_WaitAllTasksComplete_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForCompletion provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) WaitForCompletion(timeout time.Duration) error {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForCompletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerTaskExecutor_WaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForCompletion'
type MockPeerTaskExecutor_WaitForCompletion_Call struct {
	*mock.Call
}

// WaitForCompletion is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockPeerTaskExecutor_Expecter) WaitForCompletion(timeout interface{}) *MockPeerTaskExecutor_WaitForCompletion_Call {
	return &MockPeerTaskExecutor_WaitForCompletion_Call{Call: _e.mock.On("WaitForCompletion", timeout)}
}

func (_c *MockPeerTaskExecutor_WaitForCompletion_Call) Run(run func(timeout time.Duration)) *MockPeerTaskExecutor_WaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerTaskExecutor_WaitForCompletion_Call) Return(err error) *MockPeerTaskExecutor_WaitForCompletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerTaskExecutor_WaitForCompletion_Call) RunAndReturn(run func(timeout time.Duration) error) *MockPeerTaskExecutor_WaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForCompletionWithContext provides a mock function for the type MockPeerTaskExecutor
func (_mock *MockPeerTaskExecutor) WaitForCompletionWithContext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitForCompletionWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerTaskExecutor_WaitForCompletionWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForCompletionWithContext'
type MockPeerTaskExecutor_WaitForCompletionWithContext_Call struct {
	*mock.Call
}

// WaitForCompletionWithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPeerTaskExecutor_Expecter) WaitForCompletionWithContext(ctx interface{}) *MockPeerTaskExecutor_WaitForCompletionWithContext_Call {
	return &MockPeerTaskExecutor_WaitForCompletionWithContext_Call{Call: _e.mock.On("WaitForCompletionWithContext", ctx)}
}

func (_c *MockPeerTaskExecutor_WaitForCompletionWithContext_Call) Run(run func(ctx context.Context)) *MockPeerTaskExecutor_WaitForCompletionWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerTaskExecutor_WaitForCompletionWithContext_Call) Return(err error) *MockPeerTaskExecutor_WaitForCompletionWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerTaskExecutor_WaitForCompletionWithContext_Call) RunAndReturn(run func(ctx context.Context) error) *MockPeerTaskExecutor_WaitForCompletionWithContext_Call {
	_c.Call.Return(run)
	return _c
}
