// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/stream"
)

// NewMockManifestCreator creates a new instance of MockManifestCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifestCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifestCreator {
	mock := &MockManifestCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifestCreator is an autogenerated mock type for the ManifestCreator type
type MockManifestCreator struct {
	mock.Mock
}

type MockManifestCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifestCreator) EXPECT() *MockManifestCreator_Expecter {
	return &MockManifestCreator_Expecter{mock: &_m.Mock}
}

// CreateManifest provides a mock function for the type MockManifestCreator
func (_mock *MockManifestCreator) CreateManifest(source io.Reader, size int64) (*stream.SDBlob, []byte, error) {
	ret := _mock.Called(source, size)

	if len(ret) == 0 {
		panic("no return value specified for CreateManifest")
	}

	var r0 *stream.SDBlob
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader, int64) (*stream.SDBlob, []byte, error)); ok {
		return returnFunc(source, size)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader, int64) *stream.SDBlob); ok {
		r0 = returnFunc(source, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.SDBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader, int64) []byte); ok {
		r1 = returnFunc(source, size)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(io.Reader, int64) error); ok {
		r2 = returnFunc(source, size)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManifestCreator_CreateManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManifest'
type MockManifestCreator_CreateManifest_Call struct {
	*mock.Call
}

// CreateManifest is a helper method to define mock.On call
//   - source io.Reader
//   - size int64
func (_e *MockManifestCreator_Expecter) CreateManifest(source interface{}, size interface{}) *MockManifestCreator_CreateManifest_Call {
	return &MockManifestCreator_CreateManifest_Call{Call: _e.mock.On("CreateManifest", source, size)}
}

func (_c *MockManifestCreator_CreateManifest_Call) Run(run func(source io.Reader, size int64)) *MockManifestCreator_CreateManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestCreator_CreateManifest_Call) Return(sDBlob *stream.SDBlob, bytes []byte, err error) *MockManifestCreator_CreateManifest_Call {
	_c.Call.Return(sDBlob, bytes, err)
	return _c
}

func (_c *MockManifestCreator_CreateManifest_Call) RunAndReturn(run func(source io.Reader, size int64) (*stream.SDBlob, []byte, error)) *MockManifestCreator_CreateManifest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManifestFromPath provides a mock function for the type MockManifestCreator
func (_mock *MockManifestCreator) CreateManifestFromPath(path string) (*stream.SDBlob, []byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for CreateManifestFromPath")
	}

	var r0 *stream.SDBlob
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*stream.SDBlob, []byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *stream.SDBlob); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.SDBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) []byte); ok {
		r1 = returnFunc(path)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(path)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManifestCreator_CreateManifestFromPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManifestFromPath'
type MockManifestCreator_CreateManifestFromPath_Call struct {
	*mock.Call
}

// CreateManifestFromPath is a helper method to define mock.On call
//   - path string
func (_e *MockManifestCreator_Expecter) CreateManifestFromPath(path interface{}) *MockManifestCreator_CreateManifestFromPath_Call {
	return &MockManifestCreator_CreateManifestFromPath_Call{Call: _e.mock.On("CreateManifestFromPath", path)}
}

func (_c *MockManifestCreator_CreateManifestFromPath_Call) Run(run func(path string)) *MockManifestCreator_CreateManifestFromPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManifestCreator_CreateManifestFromPath_Call) Return(sDBlob *stream.SDBlob, bytes []byte, err error) *MockManifestCreator_CreateManifestFromPath_Call {
	_c.Call.Return(sDBlob, bytes, err)
	return _c
}

func (_c *MockManifestCreator_CreateManifestFromPath_Call) RunAndReturn(run func(path string) (*stream.SDBlob, []byte, error)) *MockManifestCreator_CreateManifestFromPath_Call {
	_c.Call.Return(run)
	return _c
}

// ParseManifest provides a mock function for the type MockManifestCreator
func (_mock *MockManifestCreator) ParseManifest(data []byte) (*stream.SDBlob, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ParseManifest")
	}

	var r0 *stream.SDBlob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*stream.SDBlob, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *stream.SDBlob); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stream.SDBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestCreator_ParseManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseManifest'
type MockManifestCreator_ParseManifest_Call struct {
	*mock.Call
}

// ParseManifest is a helper method to define mock.On call
//   - data []byte
func (_e *MockManifestCreator_Expecter) ParseManifest(data interface{}) *MockManifestCreator_ParseManifest_Call {
	return &MockManifestCreator_ParseManifest_Call{Call: _e.mock.On("ParseManifest", data)}
}

func (_c *MockManifestCreator_ParseManifest_Call) Run(run func(data []byte)) *MockManifestCreator_ParseManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManifestCreator_ParseManifest_Call) Return(sDBlob *stream.SDBlob, err error) *MockManifestCreator_ParseManifest_Call {
	_c.Call.Return(sDBlob, err)
	return _c
}

func (_c *MockManifestCreator_ParseManifest_Call) RunAndReturn(run func(data []byte) (*stream.SDBlob, error)) *MockManifestCreator_ParseManifest_Call {
	_c.Call.Return(run)
	return _c
}
