// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protocol

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPeerServer creates a new instance of MockPeerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerServer {
	mock := &MockPeerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerServer is an autogenerated mock type for the PeerServer type
type MockPeerServer struct {
	mock.Mock
}

type MockPeerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerServer) EXPECT() *MockPeerServer_Expecter {
	return &MockPeerServer_Expecter{mock: &_m.Mock}
}

// HandleConnection provides a mock function for the type MockPeerServer
func (_mock *MockPeerServer) HandleConnection(conn net.Conn) {
	_mock.Called(conn)
	return
}

// MockPeerServer_HandleConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnection'
type MockPeerServer_HandleConnection_Call struct {
	*mock.Call
}

// HandleConnection is a helper method to define mock.On call
//   - conn net.Conn
func (_e *MockPeerServer_Expecter) HandleConnection(conn interface{}) *MockPeerServer_HandleConnection_Call {
	return &MockPeerServer_HandleConnection_Call{Call: _e.mock.On("HandleConnection", conn)}
}

func (_c *MockPeerServer_HandleConnection_Call) Run(run func(conn net.Conn)) *MockPeerServer_HandleConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerServer_HandleConnection_Call) Return() *MockPeerServer_HandleConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerServer_HandleConnection_Call) RunAndReturn(run func(conn net.Conn)) *MockPeerServer_HandleConnection_Call {
	_c.Run(run)
	return _c
}
