// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHostResolver creates a new instance of MockHostResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostResolver {
	mock := &MockHostResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostResolver is an autogenerated mock type for the HostResolver type
type MockHostResolver struct {
	mock.Mock
}

type MockHostResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostResolver) EXPECT() *MockHostResolver_Expecter {
	return &MockHostResolver_Expecter{mock: &_m.Mock}
}

// ResolveHostToIP provides a mock function for the type MockHostResolver
func (_mock *MockHostResolver) ResolveHostToIP(host string, originalAddr string) (net.IP, error) {
	ret := _mock.Called(host, originalAddr)

	if len(ret) == 0 {
		panic("no return value specified for ResolveHostToIP")
	}

	var r0 net.IP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (net.IP, error)); ok {
		return returnFunc(host, originalAddr)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) net.IP); ok {
		r0 = returnFunc(host, originalAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(host, originalAddr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostResolver_ResolveHostToIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveHostToIP'
type MockHostResolver_ResolveHostToIP_Call struct {
	*mock.Call
}

// ResolveHostToIP is a helper method to define mock.On call
//   - host string
//   - originalAddr string
func (_e *MockHostResolver_Expecter) ResolveHostToIP(host interface{}, originalAddr interface{}) *MockHostResolver_ResolveHostToIP_Call {
	return &MockHostResolver_ResolveHostToIP_Call{Call: _e.mock.On("ResolveHostToIP", host, originalAddr)}
}

func (_c *MockHostResolver_ResolveHostToIP_Call) Run(run func(host string, originalAddr string)) *MockHostResolver_ResolveHostToIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostResolver_ResolveHostToIP_Call) Return(iP net.IP, err error) *MockHostResolver_ResolveHostToIP_Call {
	_c.Call.Return(iP, err)
	return _c
}

func (_c *MockHostResolver_ResolveHostToIP_Call) RunAndReturn(run func(host string, originalAddr string) (net.IP, error)) *MockHostResolver_ResolveHostToIP_Call {
	_c.Call.Return(run)
	return _c
}
