// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht"
	"go.lumeweb.com/lbry-dht/bits"
	"go.lumeweb.com/liblbry/protocol"
)

// NewMockPeerDiscovery creates a new instance of MockPeerDiscovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerDiscovery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerDiscovery {
	mock := &MockPeerDiscovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerDiscovery is an autogenerated mock type for the PeerDiscovery type
type MockPeerDiscovery struct {
	mock.Mock
}

type MockPeerDiscovery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerDiscovery) EXPECT() *MockPeerDiscovery_Expecter {
	return &MockPeerDiscovery_Expecter{mock: &_m.Mock}
}

// DHTNode provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) DHTNode() protocol.DHTNode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DHTNode")
	}

	var r0 protocol.DHTNode
	if returnFunc, ok := ret.Get(0).(func() protocol.DHTNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protocol.DHTNode)
		}
	}
	return r0
}

// MockPeerDiscovery_DHTNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHTNode'
type MockPeerDiscovery_DHTNode_Call struct {
	*mock.Call
}

// DHTNode is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) DHTNode() *MockPeerDiscovery_DHTNode_Call {
	return &MockPeerDiscovery_DHTNode_Call{Call: _e.mock.On("DHTNode")}
}

func (_c *MockPeerDiscovery_DHTNode_Call) Run(run func()) *MockPeerDiscovery_DHTNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_DHTNode_Call) Return(dHTNode protocol.DHTNode) *MockPeerDiscovery_DHTNode_Call {
	_c.Call.Return(dHTNode)
	return _c
}

func (_c *MockPeerDiscovery_DHTNode_Call) RunAndReturn(run func() protocol.DHTNode) *MockPeerDiscovery_DHTNode_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoverPeers provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) DiscoverPeers(ctx context.Context, hashBitmap bits.Bitmap) ([]dht.Contact, error) {
	ret := _mock.Called(ctx, hashBitmap)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverPeers")
	}

	var r0 []dht.Contact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bits.Bitmap) ([]dht.Contact, error)); ok {
		return returnFunc(ctx, hashBitmap)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bits.Bitmap) []dht.Contact); ok {
		r0 = returnFunc(ctx, hashBitmap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dht.Contact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bits.Bitmap) error); ok {
		r1 = returnFunc(ctx, hashBitmap)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerDiscovery_DiscoverPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverPeers'
type MockPeerDiscovery_DiscoverPeers_Call struct {
	*mock.Call
}

// DiscoverPeers is a helper method to define mock.On call
//   - ctx context.Context
//   - hashBitmap bits.Bitmap
func (_e *MockPeerDiscovery_Expecter) DiscoverPeers(ctx interface{}, hashBitmap interface{}) *MockPeerDiscovery_DiscoverPeers_Call {
	return &MockPeerDiscovery_DiscoverPeers_Call{Call: _e.mock.On("DiscoverPeers", ctx, hashBitmap)}
}

func (_c *MockPeerDiscovery_DiscoverPeers_Call) Run(run func(ctx context.Context, hashBitmap bits.Bitmap)) *MockPeerDiscovery_DiscoverPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bits.Bitmap
		if args[1] != nil {
			arg1 = args[1].(bits.Bitmap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerDiscovery_DiscoverPeers_Call) Return(contacts []dht.Contact, err error) *MockPeerDiscovery_DiscoverPeers_Call {
	_c.Call.Return(contacts, err)
	return _c
}

func (_c *MockPeerDiscovery_DiscoverPeers_Call) RunAndReturn(run func(ctx context.Context, hashBitmap bits.Bitmap) ([]dht.Contact, error)) *MockPeerDiscovery_DiscoverPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFixedPeers provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) GetFixedPeers() []dht.Contact {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFixedPeers")
	}

	var r0 []dht.Contact
	if returnFunc, ok := ret.Get(0).(func() []dht.Contact); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dht.Contact)
		}
	}
	return r0
}

// MockPeerDiscovery_GetFixedPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFixedPeers'
type MockPeerDiscovery_GetFixedPeers_Call struct {
	*mock.Call
}

// GetFixedPeers is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) GetFixedPeers() *MockPeerDiscovery_GetFixedPeers_Call {
	return &MockPeerDiscovery_GetFixedPeers_Call{Call: _e.mock.On("GetFixedPeers")}
}

func (_c *MockPeerDiscovery_GetFixedPeers_Call) Run(run func()) *MockPeerDiscovery_GetFixedPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_GetFixedPeers_Call) Return(contacts []dht.Contact) *MockPeerDiscovery_GetFixedPeers_Call {
	_c.Call.Return(contacts)
	return _c
}

func (_c *MockPeerDiscovery_GetFixedPeers_Call) RunAndReturn(run func() []dht.Contact) *MockPeerDiscovery_GetFixedPeers_Call {
	_c.Call.Return(run)
	return _c
}

// IsFixedPeer provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) IsFixedPeer(contact dht.Contact) bool {
	ret := _mock.Called(contact)

	if len(ret) == 0 {
		panic("no return value specified for IsFixedPeer")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(dht.Contact) bool); ok {
		r0 = returnFunc(contact)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerDiscovery_IsFixedPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFixedPeer'
type MockPeerDiscovery_IsFixedPeer_Call struct {
	*mock.Call
}

// IsFixedPeer is a helper method to define mock.On call
//   - contact dht.Contact
func (_e *MockPeerDiscovery_Expecter) IsFixedPeer(contact interface{}) *MockPeerDiscovery_IsFixedPeer_Call {
	return &MockPeerDiscovery_IsFixedPeer_Call{Call: _e.mock.On("IsFixedPeer", contact)}
}

func (_c *MockPeerDiscovery_IsFixedPeer_Call) Run(run func(contact dht.Contact)) *MockPeerDiscovery_IsFixedPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dht.Contact
		if args[0] != nil {
			arg0 = args[0].(dht.Contact)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDiscovery_IsFixedPeer_Call) Return(b bool) *MockPeerDiscovery_IsFixedPeer_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerDiscovery_IsFixedPeer_Call) RunAndReturn(run func(contact dht.Contact) bool) *MockPeerDiscovery_IsFixedPeer_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerDiscovery_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockPeerDiscovery_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) IsStopped() *MockPeerDiscovery_IsStopped_Call {
	return &MockPeerDiscovery_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockPeerDiscovery_IsStopped_Call) Run(run func()) *MockPeerDiscovery_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_IsStopped_Call) Return(b bool) *MockPeerDiscovery_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerDiscovery_IsStopped_Call) RunAndReturn(run func() bool) *MockPeerDiscovery_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// ParseFixedPeers provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) ParseFixedPeers(peerAddresses []string) ([]dht.Contact, error) {
	ret := _mock.Called(peerAddresses)

	if len(ret) == 0 {
		panic("no return value specified for ParseFixedPeers")
	}

	var r0 []dht.Contact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]dht.Contact, error)); ok {
		return returnFunc(peerAddresses)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []dht.Contact); ok {
		r0 = returnFunc(peerAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dht.Contact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(peerAddresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerDiscovery_ParseFixedPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFixedPeers'
type MockPeerDiscovery_ParseFixedPeers_Call struct {
	*mock.Call
}

// ParseFixedPeers is a helper method to define mock.On call
//   - peerAddresses []string
func (_e *MockPeerDiscovery_Expecter) ParseFixedPeers(peerAddresses interface{}) *MockPeerDiscovery_ParseFixedPeers_Call {
	return &MockPeerDiscovery_ParseFixedPeers_Call{Call: _e.mock.On("ParseFixedPeers", peerAddresses)}
}

func (_c *MockPeerDiscovery_ParseFixedPeers_Call) Run(run func(peerAddresses []string)) *MockPeerDiscovery_ParseFixedPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDiscovery_ParseFixedPeers_Call) Return(contacts []dht.Contact, err error) *MockPeerDiscovery_ParseFixedPeers_Call {
	_c.Call.Return(contacts, err)
	return _c
}

func (_c *MockPeerDiscovery_ParseFixedPeers_Call) RunAndReturn(run func(peerAddresses []string) ([]dht.Contact, error)) *MockPeerDiscovery_ParseFixedPeers_Call {
	_c.Call.Return(run)
	return _c
}

// RetryAttempts provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) RetryAttempts() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RetryAttempts")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPeerDiscovery_RetryAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryAttempts'
type MockPeerDiscovery_RetryAttempts_Call struct {
	*mock.Call
}

// RetryAttempts is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) RetryAttempts() *MockPeerDiscovery_RetryAttempts_Call {
	return &MockPeerDiscovery_RetryAttempts_Call{Call: _e.mock.On("RetryAttempts")}
}

func (_c *MockPeerDiscovery_RetryAttempts_Call) Run(run func()) *MockPeerDiscovery_RetryAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_RetryAttempts_Call) Return(n int) *MockPeerDiscovery_RetryAttempts_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPeerDiscovery_RetryAttempts_Call) RunAndReturn(run func() int) *MockPeerDiscovery_RetryAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// RetryDelay provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) RetryDelay() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RetryDelay")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockPeerDiscovery_RetryDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryDelay'
type MockPeerDiscovery_RetryDelay_Call struct {
	*mock.Call
}

// RetryDelay is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) RetryDelay() *MockPeerDiscovery_RetryDelay_Call {
	return &MockPeerDiscovery_RetryDelay_Call{Call: _e.mock.On("RetryDelay")}
}

func (_c *MockPeerDiscovery_RetryDelay_Call) Run(run func()) *MockPeerDiscovery_RetryDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_RetryDelay_Call) Return(duration time.Duration) *MockPeerDiscovery_RetryDelay_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPeerDiscovery_RetryDelay_Call) RunAndReturn(run func() time.Duration) *MockPeerDiscovery_RetryDelay_Call {
	_c.Call.Return(run)
	return _c
}

// SetFixedPeers provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) SetFixedPeers(peers []dht.Contact) {
	_mock.Called(peers)
	return
}

// MockPeerDiscovery_SetFixedPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFixedPeers'
type MockPeerDiscovery_SetFixedPeers_Call struct {
	*mock.Call
}

// SetFixedPeers is a helper method to define mock.On call
//   - peers []dht.Contact
func (_e *MockPeerDiscovery_Expecter) SetFixedPeers(peers interface{}) *MockPeerDiscovery_SetFixedPeers_Call {
	return &MockPeerDiscovery_SetFixedPeers_Call{Call: _e.mock.On("SetFixedPeers", peers)}
}

func (_c *MockPeerDiscovery_SetFixedPeers_Call) Run(run func(peers []dht.Contact)) *MockPeerDiscovery_SetFixedPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dht.Contact
		if args[0] != nil {
			arg0 = args[0].([]dht.Contact)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerDiscovery_SetFixedPeers_Call) Return() *MockPeerDiscovery_SetFixedPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDiscovery_SetFixedPeers_Call) RunAndReturn(run func(peers []dht.Contact)) *MockPeerDiscovery_SetFixedPeers_Call {
	_c.Run(run)
	return _c
}

// SetRetryConfig provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) SetRetryConfig(attempts int, delay time.Duration) {
	_mock.Called(attempts, delay)
	return
}

// MockPeerDiscovery_SetRetryConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRetryConfig'
type MockPeerDiscovery_SetRetryConfig_Call struct {
	*mock.Call
}

// SetRetryConfig is a helper method to define mock.On call
//   - attempts int
//   - delay time.Duration
func (_e *MockPeerDiscovery_Expecter) SetRetryConfig(attempts interface{}, delay interface{}) *MockPeerDiscovery_SetRetryConfig_Call {
	return &MockPeerDiscovery_SetRetryConfig_Call{Call: _e.mock.On("SetRetryConfig", attempts, delay)}
}

func (_c *MockPeerDiscovery_SetRetryConfig_Call) Run(run func(attempts int, delay time.Duration)) *MockPeerDiscovery_SetRetryConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerDiscovery_SetRetryConfig_Call) Return() *MockPeerDiscovery_SetRetryConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDiscovery_SetRetryConfig_Call) RunAndReturn(run func(attempts int, delay time.Duration)) *MockPeerDiscovery_SetRetryConfig_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) Start() {
	_mock.Called()
	return
}

// MockPeerDiscovery_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPeerDiscovery_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) Start() *MockPeerDiscovery_Start_Call {
	return &MockPeerDiscovery_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPeerDiscovery_Start_Call) Run(run func()) *MockPeerDiscovery_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_Start_Call) Return() *MockPeerDiscovery_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDiscovery_Start_Call) RunAndReturn(run func()) *MockPeerDiscovery_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockPeerDiscovery
func (_mock *MockPeerDiscovery) Stop() {
	_mock.Called()
	return
}

// MockPeerDiscovery_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPeerDiscovery_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPeerDiscovery_Expecter) Stop() *MockPeerDiscovery_Stop_Call {
	return &MockPeerDiscovery_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPeerDiscovery_Stop_Call) Run(run func()) *MockPeerDiscovery_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerDiscovery_Stop_Call) Return() *MockPeerDiscovery_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerDiscovery_Stop_Call) RunAndReturn(run func()) *MockPeerDiscovery_Stop_Call {
	_c.Run(run)
	return _c
}
