// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht/bits"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/coordinator"
	"go.uber.org/zap"
)

// NewMockPhaseManager creates a new instance of MockPhaseManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhaseManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhaseManager {
	mock := &MockPhaseManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPhaseManager is an autogenerated mock type for the PhaseManager type
type MockPhaseManager struct {
	mock.Mock
}

type MockPhaseManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhaseManager) EXPECT() *MockPhaseManager_Expecter {
	return &MockPhaseManager_Expecter{mock: &_m.Mock}
}

// ExecutePhases provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) ExecutePhases(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest) ([]byte, error) {
	ret := _mock.Called(ctx, hash, hashBitmap, req)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePhases")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) ([]byte, error)); ok {
		return returnFunc(ctx, hash, hashBitmap, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) []byte); ok {
		r0 = returnFunc(ctx, hash, hashBitmap, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bits.Bitmap, *blob.BlobRequest) error); ok {
		r1 = returnFunc(ctx, hash, hashBitmap, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhaseManager_ExecutePhases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutePhases'
type MockPhaseManager_ExecutePhases_Call struct {
	*mock.Call
}

// ExecutePhases is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - hashBitmap bits.Bitmap
//   - req *blob.BlobRequest
func (_e *MockPhaseManager_Expecter) ExecutePhases(ctx interface{}, hash interface{}, hashBitmap interface{}, req interface{}) *MockPhaseManager_ExecutePhases_Call {
	return &MockPhaseManager_ExecutePhases_Call{Call: _e.mock.On("ExecutePhases", ctx, hash, hashBitmap, req)}
}

func (_c *MockPhaseManager_ExecutePhases_Call) Run(run func(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest)) *MockPhaseManager_ExecutePhases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bits.Bitmap
		if args[2] != nil {
			arg2 = args[2].(bits.Bitmap)
		}
		var arg3 *blob.BlobRequest
		if args[3] != nil {
			arg3 = args[3].(*blob.BlobRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPhaseManager_ExecutePhases_Call) Return(bytes []byte, err error) *MockPhaseManager_ExecutePhases_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPhaseManager_ExecutePhases_Call) RunAndReturn(run func(ctx context.Context, hash string, hashBitmap bits.Bitmap, req *blob.BlobRequest) ([]byte, error)) *MockPhaseManager_ExecutePhases_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxPeers provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) GetMaxPeers() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxPeers")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockPhaseManager_GetMaxPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxPeers'
type MockPhaseManager_GetMaxPeers_Call struct {
	*mock.Call
}

// GetMaxPeers is a helper method to define mock.On call
func (_e *MockPhaseManager_Expecter) GetMaxPeers() *MockPhaseManager_GetMaxPeers_Call {
	return &MockPhaseManager_GetMaxPeers_Call{Call: _e.mock.On("GetMaxPeers")}
}

func (_c *MockPhaseManager_GetMaxPeers_Call) Run(run func()) *MockPhaseManager_GetMaxPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPhaseManager_GetMaxPeers_Call) Return(n int32) *MockPhaseManager_GetMaxPeers_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPhaseManager_GetMaxPeers_Call) RunAndReturn(run func() int32) *MockPhaseManager_GetMaxPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetRaceCoordinator provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) GetRaceCoordinator() coordinator.PeerRaceCoordinator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRaceCoordinator")
	}

	var r0 coordinator.PeerRaceCoordinator
	if returnFunc, ok := ret.Get(0).(func() coordinator.PeerRaceCoordinator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinator.PeerRaceCoordinator)
		}
	}
	return r0
}

// MockPhaseManager_GetRaceCoordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRaceCoordinator'
type MockPhaseManager_GetRaceCoordinator_Call struct {
	*mock.Call
}

// GetRaceCoordinator is a helper method to define mock.On call
func (_e *MockPhaseManager_Expecter) GetRaceCoordinator() *MockPhaseManager_GetRaceCoordinator_Call {
	return &MockPhaseManager_GetRaceCoordinator_Call{Call: _e.mock.On("GetRaceCoordinator")}
}

func (_c *MockPhaseManager_GetRaceCoordinator_Call) Run(run func()) *MockPhaseManager_GetRaceCoordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPhaseManager_GetRaceCoordinator_Call) Return(peerRaceCoordinator coordinator.PeerRaceCoordinator) *MockPhaseManager_GetRaceCoordinator_Call {
	_c.Call.Return(peerRaceCoordinator)
	return _c
}

func (_c *MockPhaseManager_GetRaceCoordinator_Call) RunAndReturn(run func() coordinator.PeerRaceCoordinator) *MockPhaseManager_GetRaceCoordinator_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPhaseManager_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockPhaseManager_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockPhaseManager_Expecter) IsStopped() *MockPhaseManager_IsStopped_Call {
	return &MockPhaseManager_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockPhaseManager_IsStopped_Call) Run(run func()) *MockPhaseManager_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPhaseManager_IsStopped_Call) Return(b bool) *MockPhaseManager_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPhaseManager_IsStopped_Call) RunAndReturn(run func() bool) *MockPhaseManager_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogger provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) SetLogger(logger *zap.Logger) {
	_mock.Called(logger)
	return
}

// MockPhaseManager_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockPhaseManager_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *zap.Logger
func (_e *MockPhaseManager_Expecter) SetLogger(logger interface{}) *MockPhaseManager_SetLogger_Call {
	return &MockPhaseManager_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockPhaseManager_SetLogger_Call) Run(run func(logger *zap.Logger)) *MockPhaseManager_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zap.Logger
		if args[0] != nil {
			arg0 = args[0].(*zap.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPhaseManager_SetLogger_Call) Return() *MockPhaseManager_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPhaseManager_SetLogger_Call) RunAndReturn(run func(logger *zap.Logger)) *MockPhaseManager_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetMaxPeers provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) SetMaxPeers(maxPeers int) {
	_mock.Called(maxPeers)
	return
}

// MockPhaseManager_SetMaxPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxPeers'
type MockPhaseManager_SetMaxPeers_Call struct {
	*mock.Call
}

// SetMaxPeers is a helper method to define mock.On call
//   - maxPeers int
func (_e *MockPhaseManager_Expecter) SetMaxPeers(maxPeers interface{}) *MockPhaseManager_SetMaxPeers_Call {
	return &MockPhaseManager_SetMaxPeers_Call{Call: _e.mock.On("SetMaxPeers", maxPeers)}
}

func (_c *MockPhaseManager_SetMaxPeers_Call) Run(run func(maxPeers int)) *MockPhaseManager_SetMaxPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPhaseManager_SetMaxPeers_Call) Return() *MockPhaseManager_SetMaxPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPhaseManager_SetMaxPeers_Call) RunAndReturn(run func(maxPeers int)) *MockPhaseManager_SetMaxPeers_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) Start() {
	_mock.Called()
	return
}

// MockPhaseManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPhaseManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPhaseManager_Expecter) Start() *MockPhaseManager_Start_Call {
	return &MockPhaseManager_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPhaseManager_Start_Call) Run(run func()) *MockPhaseManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPhaseManager_Start_Call) Return() *MockPhaseManager_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPhaseManager_Start_Call) RunAndReturn(run func()) *MockPhaseManager_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockPhaseManager
func (_mock *MockPhaseManager) Stop() {
	_mock.Called()
	return
}

// MockPhaseManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPhaseManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPhaseManager_Expecter) Stop() *MockPhaseManager_Stop_Call {
	return &MockPhaseManager_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPhaseManager_Stop_Call) Run(run func()) *MockPhaseManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPhaseManager_Stop_Call) Return() *MockPhaseManager_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPhaseManager_Stop_Call) RunAndReturn(run func()) *MockPhaseManager_Stop_Call {
	_c.Run(run)
	return _c
}
