// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stream

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHashIdentifier creates a new instance of MockHashIdentifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashIdentifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashIdentifier {
	mock := &MockHashIdentifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHashIdentifier is an autogenerated mock type for the HashIdentifier type
type MockHashIdentifier struct {
	mock.Mock
}

type MockHashIdentifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashIdentifier) EXPECT() *MockHashIdentifier_Expecter {
	return &MockHashIdentifier_Expecter{mock: &_m.Mock}
}

// Identify provides a mock function for the type MockHashIdentifier
func (_mock *MockHashIdentifier) Identify(hash string) HashType {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Identify")
	}

	var r0 HashType
	if returnFunc, ok := ret.Get(0).(func(string) HashType); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(HashType)
	}
	return r0
}

// MockHashIdentifier_Identify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identify'
type MockHashIdentifier_Identify_Call struct {
	*mock.Call
}

// Identify is a helper method to define mock.On call
//   - hash string
func (_e *MockHashIdentifier_Expecter) Identify(hash interface{}) *MockHashIdentifier_Identify_Call {
	return &MockHashIdentifier_Identify_Call{Call: _e.mock.On("Identify", hash)}
}

func (_c *MockHashIdentifier_Identify_Call) Run(run func(hash string)) *MockHashIdentifier_Identify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHashIdentifier_Identify_Call) Return(hashType HashType) *MockHashIdentifier_Identify_Call {
	_c.Call.Return(hashType)
	return _c
}

func (_c *MockHashIdentifier_Identify_Call) RunAndReturn(run func(hash string) HashType) *MockHashIdentifier_Identify_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockHashIdentifier
func (_mock *MockHashIdentifier) Validate(hash string) bool {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHashIdentifier_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockHashIdentifier_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - hash string
func (_e *MockHashIdentifier_Expecter) Validate(hash interface{}) *MockHashIdentifier_Validate_Call {
	return &MockHashIdentifier_Validate_Call{Call: _e.mock.On("Validate", hash)}
}

func (_c *MockHashIdentifier_Validate_Call) Run(run func(hash string)) *MockHashIdentifier_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHashIdentifier_Validate_Call) Return(b bool) *MockHashIdentifier_Validate_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHashIdentifier_Validate_Call) RunAndReturn(run func(hash string) bool) *MockHashIdentifier_Validate_Call {
	_c.Call.Return(run)
	return _c
}
