// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stream

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamReaderFactory creates a new instance of MockStreamReaderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamReaderFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamReaderFactory {
	mock := &MockStreamReaderFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamReaderFactory is an autogenerated mock type for the StreamReaderFactory type
type MockStreamReaderFactory struct {
	mock.Mock
}

type MockStreamReaderFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamReaderFactory) EXPECT() *MockStreamReaderFactory_Expecter {
	return &MockStreamReaderFactory_Expecter{mock: &_m.Mock}
}

// NewStreamReader provides a mock function for the type MockStreamReaderFactory
func (_mock *MockStreamReaderFactory) NewStreamReader(path string) (StreamReader, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for NewStreamReader")
	}

	var r0 StreamReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (StreamReader, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) StreamReader); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(StreamReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamReaderFactory_NewStreamReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStreamReader'
type MockStreamReaderFactory_NewStreamReader_Call struct {
	*mock.Call
}

// NewStreamReader is a helper method to define mock.On call
//   - path string
func (_e *MockStreamReaderFactory_Expecter) NewStreamReader(path interface{}) *MockStreamReaderFactory_NewStreamReader_Call {
	return &MockStreamReaderFactory_NewStreamReader_Call{Call: _e.mock.On("NewStreamReader", path)}
}

func (_c *MockStreamReaderFactory_NewStreamReader_Call) Run(run func(path string)) *MockStreamReaderFactory_NewStreamReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamReaderFactory_NewStreamReader_Call) Return(streamReader StreamReader, err error) *MockStreamReaderFactory_NewStreamReader_Call {
	_c.Call.Return(streamReader, err)
	return _c
}

func (_c *MockStreamReaderFactory_NewStreamReader_Call) RunAndReturn(run func(path string) (StreamReader, error)) *MockStreamReaderFactory_NewStreamReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreamReaderFromReader provides a mock function for the type MockStreamReaderFactory
func (_mock *MockStreamReaderFactory) NewStreamReaderFromReader(r any) (StreamReader, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for NewStreamReaderFromReader")
	}

	var r0 StreamReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (StreamReader, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(any) StreamReader); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(StreamReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamReaderFactory_NewStreamReaderFromReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStreamReaderFromReader'
type MockStreamReaderFactory_NewStreamReaderFromReader_Call struct {
	*mock.Call
}

// NewStreamReaderFromReader is a helper method to define mock.On call
//   - r any
func (_e *MockStreamReaderFactory_Expecter) NewStreamReaderFromReader(r interface{}) *MockStreamReaderFactory_NewStreamReaderFromReader_Call {
	return &MockStreamReaderFactory_NewStreamReaderFromReader_Call{Call: _e.mock.On("NewStreamReaderFromReader", r)}
}

func (_c *MockStreamReaderFactory_NewStreamReaderFromReader_Call) Run(run func(r any)) *MockStreamReaderFactory_NewStreamReaderFromReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamReaderFactory_NewStreamReaderFromReader_Call) Return(streamReader StreamReader, err error) *MockStreamReaderFactory_NewStreamReaderFromReader_Call {
	_c.Call.Return(streamReader, err)
	return _c
}

func (_c *MockStreamReaderFactory_NewStreamReaderFromReader_Call) RunAndReturn(run func(r any) (StreamReader, error)) *MockStreamReaderFactory_NewStreamReaderFromReader_Call {
	_c.Call.Return(run)
	return _c
}
