// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobTransfer creates a new instance of MockBlobTransfer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobTransfer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobTransfer {
	mock := &MockBlobTransfer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobTransfer is an autogenerated mock type for the BlobTransfer type
type MockBlobTransfer struct {
	mock.Mock
}

type MockBlobTransfer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobTransfer) EXPECT() *MockBlobTransfer_Expecter {
	return &MockBlobTransfer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBlobTransfer
func (_mock *MockBlobTransfer) Get(hash string) ([]byte, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobTransfer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlobTransfer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash string
func (_e *MockBlobTransfer_Expecter) Get(hash interface{}) *MockBlobTransfer_Get_Call {
	return &MockBlobTransfer_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockBlobTransfer_Get_Call) Run(run func(hash string)) *MockBlobTransfer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlobTransfer_Get_Call) Return(bytes []byte, err error) *MockBlobTransfer_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockBlobTransfer_Get_Call) RunAndReturn(run func(hash string) ([]byte, error)) *MockBlobTransfer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockBlobTransfer
func (_mock *MockBlobTransfer) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBlobTransfer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockBlobTransfer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockBlobTransfer_Expecter) Name() *MockBlobTransfer_Name_Call {
	return &MockBlobTransfer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockBlobTransfer_Name_Call) Run(run func()) *MockBlobTransfer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlobTransfer_Name_Call) Return(s string) *MockBlobTransfer_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBlobTransfer_Name_Call) RunAndReturn(run func() string) *MockBlobTransfer_Name_Call {
	_c.Call.Return(run)
	return _c
}
