// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobAcquirer creates a new instance of MockBlobAcquirer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobAcquirer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobAcquirer {
	mock := &MockBlobAcquirer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobAcquirer is an autogenerated mock type for the BlobAcquirer type
type MockBlobAcquirer struct {
	mock.Mock
}

type MockBlobAcquirer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobAcquirer) EXPECT() *MockBlobAcquirer_Expecter {
	return &MockBlobAcquirer_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type MockBlobAcquirer
func (_mock *MockBlobAcquirer) Acquire(ctx context.Context, hash string) ([]byte, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobAcquirer_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockBlobAcquirer_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockBlobAcquirer_Expecter) Acquire(ctx interface{}, hash interface{}) *MockBlobAcquirer_Acquire_Call {
	return &MockBlobAcquirer_Acquire_Call{Call: _e.mock.On("Acquire", ctx, hash)}
}

func (_c *MockBlobAcquirer_Acquire_Call) Run(run func(ctx context.Context, hash string)) *MockBlobAcquirer_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobAcquirer_Acquire_Call) Return(bytes []byte, err error) *MockBlobAcquirer_Acquire_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockBlobAcquirer_Acquire_Call) RunAndReturn(run func(ctx context.Context, hash string) ([]byte, error)) *MockBlobAcquirer_Acquire_Call {
	_c.Call.Return(run)
	return _c
}
