// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockLoggerGetter creates a new instance of MockLoggerGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerGetter {
	mock := &MockLoggerGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerGetter is an autogenerated mock type for the LoggerGetter type
type MockLoggerGetter struct {
	mock.Mock
}

type MockLoggerGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerGetter) EXPECT() *MockLoggerGetter_Expecter {
	return &MockLoggerGetter_Expecter{mock: &_m.Mock}
}

// GetLogger provides a mock function for the type MockLoggerGetter
func (_mock *MockLoggerGetter) GetLogger() *zap.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 *zap.Logger
	if returnFunc, ok := ret.Get(0).(func() *zap.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zap.Logger)
		}
	}
	return r0
}

// MockLoggerGetter_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockLoggerGetter_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockLoggerGetter_Expecter) GetLogger() *MockLoggerGetter_GetLogger_Call {
	return &MockLoggerGetter_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockLoggerGetter_GetLogger_Call) Run(run func()) *MockLoggerGetter_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerGetter_GetLogger_Call) Return(logger *zap.Logger) *MockLoggerGetter_GetLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLoggerGetter_GetLogger_Call) RunAndReturn(run func() *zap.Logger) *MockLoggerGetter_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}
