// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReflectorClient creates a new instance of MockReflectorClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReflectorClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReflectorClient {
	mock := &MockReflectorClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReflectorClient is an autogenerated mock type for the ReflectorClient type
type MockReflectorClient struct {
	mock.Mock
}

type MockReflectorClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReflectorClient) EXPECT() *MockReflectorClient_Expecter {
	return &MockReflectorClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockReflectorClient
func (_mock *MockReflectorClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReflectorClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReflectorClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReflectorClient_Expecter) Close() *MockReflectorClient_Close_Call {
	return &MockReflectorClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReflectorClient_Close_Call) Run(run func()) *MockReflectorClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReflectorClient_Close_Call) Return(err error) *MockReflectorClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReflectorClient_Close_Call) RunAndReturn(run func() error) *MockReflectorClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockReflectorClient
func (_mock *MockReflectorClient) Connect(address string) error {
	ret := _mock.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReflectorClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockReflectorClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - address string
func (_e *MockReflectorClient_Expecter) Connect(address interface{}) *MockReflectorClient_Connect_Call {
	return &MockReflectorClient_Connect_Call{Call: _e.mock.On("Connect", address)}
}

func (_c *MockReflectorClient_Connect_Call) Run(run func(address string)) *MockReflectorClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReflectorClient_Connect_Call) Return(err error) *MockReflectorClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReflectorClient_Connect_Call) RunAndReturn(run func(address string) error) *MockReflectorClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockReflectorClient
func (_mock *MockReflectorClient) Get(hash string) ([]byte, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReflectorClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReflectorClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash string
func (_e *MockReflectorClient_Expecter) Get(hash interface{}) *MockReflectorClient_Get_Call {
	return &MockReflectorClient_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockReflectorClient_Get_Call) Run(run func(hash string)) *MockReflectorClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReflectorClient_Get_Call) Return(bytes []byte, err error) *MockReflectorClient_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReflectorClient_Get_Call) RunAndReturn(run func(hash string) ([]byte, error)) *MockReflectorClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SendBlob provides a mock function for the type MockReflectorClient
func (_mock *MockReflectorClient) SendBlob(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReflectorClient_SendBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBlob'
type MockReflectorClient_SendBlob_Call struct {
	*mock.Call
}

// SendBlob is a helper method to define mock.On call
//   - data []byte
func (_e *MockReflectorClient_Expecter) SendBlob(data interface{}) *MockReflectorClient_SendBlob_Call {
	return &MockReflectorClient_SendBlob_Call{Call: _e.mock.On("SendBlob", data)}
}

func (_c *MockReflectorClient_SendBlob_Call) Run(run func(data []byte)) *MockReflectorClient_SendBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReflectorClient_SendBlob_Call) Return(err error) *MockReflectorClient_SendBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReflectorClient_SendBlob_Call) RunAndReturn(run func(data []byte) error) *MockReflectorClient_SendBlob_Call {
	_c.Call.Return(run)
	return _c
}

// SendSDBlob provides a mock function for the type MockReflectorClient
func (_mock *MockReflectorClient) SendSDBlob(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendSDBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReflectorClient_SendSDBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSDBlob'
type MockReflectorClient_SendSDBlob_Call struct {
	*mock.Call
}

// SendSDBlob is a helper method to define mock.On call
//   - data []byte
func (_e *MockReflectorClient_Expecter) SendSDBlob(data interface{}) *MockReflectorClient_SendSDBlob_Call {
	return &MockReflectorClient_SendSDBlob_Call{Call: _e.mock.On("SendSDBlob", data)}
}

func (_c *MockReflectorClient_SendSDBlob_Call) Run(run func(data []byte)) *MockReflectorClient_SendSDBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReflectorClient_SendSDBlob_Call) Return(err error) *MockReflectorClient_SendSDBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReflectorClient_SendSDBlob_Call) RunAndReturn(run func(data []byte) error) *MockReflectorClient_SendSDBlob_Call {
	_c.Call.Return(run)
	return _c
}
