// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/knadh/koanf/v2"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry"
)

// NewMockStoreFactory creates a new instance of MockStoreFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreFactory {
	mock := &MockStoreFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreFactory is an autogenerated mock type for the StoreFactory type
type MockStoreFactory struct {
	mock.Mock
}

type MockStoreFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreFactory) EXPECT() *MockStoreFactory_Expecter {
	return &MockStoreFactory_Expecter{mock: &_m.Mock}
}

// CreateStore provides a mock function for the type MockStoreFactory
func (_mock *MockStoreFactory) CreateStore(config *koanf.Koanf) (liblbry.BlobStore, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 liblbry.BlobStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*koanf.Koanf) (liblbry.BlobStore, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(*koanf.Koanf) liblbry.BlobStore); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(liblbry.BlobStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*koanf.Koanf) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreFactory_CreateStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStore'
type MockStoreFactory_CreateStore_Call struct {
	*mock.Call
}

// CreateStore is a helper method to define mock.On call
//   - config *koanf.Koanf
func (_e *MockStoreFactory_Expecter) CreateStore(config interface{}) *MockStoreFactory_CreateStore_Call {
	return &MockStoreFactory_CreateStore_Call{Call: _e.mock.On("CreateStore", config)}
}

func (_c *MockStoreFactory_CreateStore_Call) Run(run func(config *koanf.Koanf)) *MockStoreFactory_CreateStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *koanf.Koanf
		if args[0] != nil {
			arg0 = args[0].(*koanf.Koanf)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreFactory_CreateStore_Call) Return(blobStore liblbry.BlobStore, err error) *MockStoreFactory_CreateStore_Call {
	_c.Call.Return(blobStore, err)
	return _c
}

func (_c *MockStoreFactory_CreateStore_Call) RunAndReturn(run func(config *koanf.Koanf) (liblbry.BlobStore, error)) *MockStoreFactory_CreateStore_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockStoreFactory
func (_mock *MockStoreFactory) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStoreFactory_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockStoreFactory_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockStoreFactory_Expecter) Name() *MockStoreFactory_Name_Call {
	return &MockStoreFactory_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockStoreFactory_Name_Call) Run(run func()) *MockStoreFactory_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStoreFactory_Name_Call) Return(s string) *MockStoreFactory_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStoreFactory_Name_Call) RunAndReturn(run func() string) *MockStoreFactory_Name_Call {
	_c.Call.Return(run)
	return _c
}
