// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreFactoryOption creates a new instance of MockStoreFactoryOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreFactoryOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreFactoryOption {
	mock := &MockStoreFactoryOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreFactoryOption is an autogenerated mock type for the StoreFactoryOption type
type MockStoreFactoryOption struct {
	mock.Mock
}

type MockStoreFactoryOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreFactoryOption) EXPECT() *MockStoreFactoryOption_Expecter {
	return &MockStoreFactoryOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockStoreFactoryOption
func (_mock *MockStoreFactoryOption) Apply(ifaceVal interface{}) error {
	ret := _mock.Called(ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(ifaceVal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreFactoryOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockStoreFactoryOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ifaceVal interface{}
func (_e *MockStoreFactoryOption_Expecter) Apply(ifaceVal interface{}) *MockStoreFactoryOption_Apply_Call {
	return &MockStoreFactoryOption_Apply_Call{Call: _e.mock.On("Apply", ifaceVal)}
}

func (_c *MockStoreFactoryOption_Apply_Call) Run(run func(ifaceVal interface{})) *MockStoreFactoryOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreFactoryOption_Apply_Call) Return(err error) *MockStoreFactoryOption_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreFactoryOption_Apply_Call) RunAndReturn(run func(ifaceVal interface{}) error) *MockStoreFactoryOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}
