// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransfer creates a new instance of MockTransfer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransfer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransfer {
	mock := &MockTransfer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransfer is an autogenerated mock type for the Transfer type
type MockTransfer struct {
	mock.Mock
}

type MockTransfer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransfer) EXPECT() *MockTransfer_Expecter {
	return &MockTransfer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockTransfer
func (_mock *MockTransfer) Get(hash string) ([]byte, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransfer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransfer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash string
func (_e *MockTransfer_Expecter) Get(hash interface{}) *MockTransfer_Get_Call {
	return &MockTransfer_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockTransfer_Get_Call) Run(run func(hash string)) *MockTransfer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransfer_Get_Call) Return(bytes []byte, err error) *MockTransfer_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTransfer_Get_Call) RunAndReturn(run func(hash string) ([]byte, error)) *MockTransfer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTransfer
func (_mock *MockTransfer) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTransfer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTransfer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTransfer_Expecter) Name() *MockTransfer_Name_Call {
	return &MockTransfer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTransfer_Name_Call) Run(run func()) *MockTransfer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransfer_Name_Call) Return(s string) *MockTransfer_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTransfer_Name_Call) RunAndReturn(run func() string) *MockTransfer_Name_Call {
	_c.Call.Return(run)
	return _c
}
