// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransferOption creates a new instance of MockTransferOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferOption {
	mock := &MockTransferOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransferOption is an autogenerated mock type for the TransferOption type
type MockTransferOption struct {
	mock.Mock
}

type MockTransferOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferOption) EXPECT() *MockTransferOption_Expecter {
	return &MockTransferOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockTransferOption
func (_mock *MockTransferOption) Apply(transfer any) error {
	ret := _mock.Called(transfer)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(transfer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockTransferOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - transfer any
func (_e *MockTransferOption_Expecter) Apply(transfer interface{}) *MockTransferOption_Apply_Call {
	return &MockTransferOption_Apply_Call{Call: _e.mock.On("Apply", transfer)}
}

func (_c *MockTransferOption_Apply_Call) Run(run func(transfer any)) *MockTransferOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransferOption_Apply_Call) Return(err error) *MockTransferOption_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferOption_Apply_Call) RunAndReturn(run func(transfer any) error) *MockTransferOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}
