package memory

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	libtesting "go.lumeweb.com/liblbry/internal/testing"
)


// Invalid hash test cases generated by generate_invalid_hashes.go
var invalidHashCases = []struct {
	name        string
	hash        string
	expectError bool
}{
	{
		name:        "short hash",
		hash:        "abc123",
		expectError: true,
	}, // too short (less than 96 chars)
	{
		name:        "long hash",
		hash:        "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
		expectError: true,
	}, // too long (more than 96 chars)
	{
		name:        "non-hex characters",
		hash:        "g2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6e",
		expectError: true,
	}, // contains non-hex character 'g'
	{
		name:        "mixed case non-hex",
		hash:        "G2F1841BB9C5F3B583AC3B8C07EE1A5BF9CC48923721C30D5CA6318615776C284E8936D72FA4DB7FDDA2E4E9598B1E6E",
		expectError: true,
	}, // contains uppercase non-hex characters
	{
		name:        "special characters",
		hash:        "a2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6!",
		expectError: true,
	}, // contains special character '!'
	{
		name:        "empty hash",
		hash:        "",
		expectError: true,
	}, // completely empty
	{
		name:        "spaces in hash",
		hash:        "a2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6 ",
		expectError: true,
	}, // contains trailing space
	{
		name:        "unicode characters",
		hash:        "a2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6世界",
		expectError: true,
	}, // contains unicode characters
}

func TestMemoryStore(t *testing.T) {
	store := NewMemoryStore()

	// Test Name method
	t.Run("Name", func(t *testing.T) {
		assert.Equal(t, "memory", store.Name())
	})

	// Test Has method
	t.Run("Has", func(t *testing.T) {
		tests := []struct {
			name     string
			hash     string
			data     []byte
			expected bool
			setup    bool
		}{
			{
				name:     "existing blob",
				hash:     "a2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6c",
				data:     []byte("test data 1"),
				expected: true,
				setup:    true,
			},
			{
				name:     "non-existing blob",
				hash:     "0c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5cb",
				expected: false,
				setup:    false,
			},
			{
				name:     "empty hash",
				hash:     "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
				expected: false,
				setup:    false,
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				store := NewMemoryStore()
				if tt.setup {
					err := store.Put(tt.hash, tt.data)
					require.NoError(t, err)
				}

				exists, err := store.Has(tt.hash)
				require.NoError(t, err)
				assert.Equal(t, tt.expected, exists)
			})
		}
	})

	// Test Get method
	t.Run("Get", func(t *testing.T) {
		tests := []struct {
			name        string
			hash        string
			data        []byte
			expectError bool
			setup       bool
		}{
			{
				name:        "existing blob",
				hash:        "b2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6d",
				data:        []byte("test data 2"),
				expectError: false,
				setup:       true,
			},
			{
				name:        "non-existing blob",
				hash:        "1c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5cc",
				expectError: true,
				setup:       false,
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				store := NewMemoryStore()
				if tt.setup {
					err := store.Put(tt.hash, tt.data)
					require.NoError(t, err)
				}

				data, err := store.Get(tt.hash)
				if tt.expectError {
					assert.Error(t, err)
					assert.Nil(t, data)
				} else {
					require.NoError(t, err)
					assert.Equal(t, tt.data, data)
				}
			})
		}
	})

	// Test Put method
	t.Run("Put", func(t *testing.T) {
		tests := []struct {
			name        string
			hash        string
			data        []byte
			expectError bool
		}{
			{
				name:        "valid data",
				hash:        "c2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6e",
				data:        []byte("test data 3"),
				expectError: false,
			},
			{
				name:        "empty data",
				hash:        "2c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5cd",
				data:        []byte{},
				expectError: true,
			},
			{
				name:        "nil data",
				hash:        "3c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5ce",
				data:        nil,
				expectError: true,
			},
		}

		// Add invalid hash cases
		for _, invalidCase := range invalidHashCases {
			tests = append(tests, struct {
				name        string
				hash        string
				data        []byte
				expectError bool
			}{
				name:        "invalid hash: " + invalidCase.name,
				hash:        invalidCase.hash,
				data:        []byte("test data for invalid hash"),
				expectError: true,
			})
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				store := NewMemoryStore()
				err := store.Put(tt.hash, tt.data)
				if tt.expectError {
					assert.Error(t, err)
				} else {
					assert.NoError(t, err)

					// Verify the data was stored
					data, err := store.Get(tt.hash)
					require.NoError(t, err)
					assert.Equal(t, tt.data, data)
				}
			})
		}
	})

	// Test PutSD method
	t.Run("PutSD", func(t *testing.T) {
		tests := []struct {
			name        string
			hash        string
			data        []byte
			expectError bool
		}{
			{
				name:        "valid SD data",
				hash:        "d2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e6f",
				data:        []byte("sd test data 1"),
				expectError: false,
			},
			{
				name:        "empty SD data",
				hash:        "4c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5cf",
				data:        []byte{},
				expectError: true,
			},
			{
				name:        "nil SD data",
				hash:        "5c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5d0",
				data:        nil,
				expectError: true,
			},
		}

		// Add invalid hash cases
		for _, invalidCase := range invalidHashCases {
			tests = append(tests, struct {
				name        string
				hash        string
				data        []byte
				expectError bool
			}{
				name:        "invalid SD hash: " + invalidCase.name,
				hash:        invalidCase.hash,
				data:        []byte("sd test data for invalid hash"),
				expectError: true,
			})
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				store := NewMemoryStore()
				err := store.PutSD(tt.hash, tt.data)
				if tt.expectError {
					assert.Error(t, err)
				} else {
					assert.NoError(t, err)

					// Verify the SD data was stored
					data, err := store.Get(tt.hash)
					require.NoError(t, err)
					assert.Equal(t, tt.data, data)
				}
			})
		}
	})

	// Test integration between regular blobs and SD blobs
	t.Run("BlobSDIntegration", func(t *testing.T) {
		store := NewMemoryStore()

		regularHash := "e2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e60"
		sdHash := "6c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5d1"
		regularData := []byte("regular data")
		sdData := []byte("sd data")

		// Put regular blob
		err := store.Put(regularHash, regularData)
		require.NoError(t, err)

		// Put SD blob
		err = store.PutSD(sdHash, sdData)
		require.NoError(t, err)

		// Verify both exist
		exists, err := store.Has(regularHash)
		require.NoError(t, err)
		assert.True(t, exists)

		exists, err = store.Has(sdHash)
		require.NoError(t, err)
		assert.True(t, exists)

		// Verify data is correct
		data, err := store.Get(regularHash)
		require.NoError(t, err)
		assert.Equal(t, regularData, data)

		data, err = store.Get(sdHash)
		require.NoError(t, err)
		assert.Equal(t, sdData, data)
	})

	// Test hash collision behavior between regular and SD blobs
	t.Run("HashCollisionBehavior", func(t *testing.T) {
		store := NewMemoryStore()

		collisionHash := "f2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e61"
		regularData := []byte("regular blob data")
		sdData := []byte("sd blob data")

		// Test case 1: Regular blob stored first, then SD blob with same hash
		err := store.Put(collisionHash, regularData)
		require.NoError(t, err)

		err = store.PutSD(collisionHash, sdData)
		require.NoError(t, err)

		// Has should return true (blob exists)
		exists, err := store.Has(collisionHash)
		require.NoError(t, err)
		assert.True(t, exists)

		// Get should return regular blob data (priority over SD)
		data, err := store.Get(collisionHash)
		require.NoError(t, err)
		assert.Equal(t, regularData, data, "Get should prioritize regular blob over SD blob")

		// Test case 2: SD blob stored first, then regular blob with same hash
		store = NewMemoryStore() // Fresh store

		err = store.PutSD(collisionHash, sdData)
		require.NoError(t, err)

		err = store.Put(collisionHash, regularData)
		require.NoError(t, err)

		// Has should return true (blob exists)
		exists, err = store.Has(collisionHash)
		require.NoError(t, err)
		assert.True(t, exists)

		// Get should still return regular blob data (priority over SD)
		data, err = store.Get(collisionHash)
		require.NoError(t, err)
		assert.Equal(t, regularData, data, "Get should prioritize regular blob over SD blob regardless of storage order")

		// Test case 3: Only SD blob exists
		store = NewMemoryStore() // Fresh store

		err = store.PutSD(collisionHash, sdData)
		require.NoError(t, err)

		// Has should return true
		exists, err = store.Has(collisionHash)
		require.NoError(t, err)
		assert.True(t, exists)

		// Get should return SD blob data (no regular blob to prioritize)
		data, err = store.Get(collisionHash)
		require.NoError(t, err)
		assert.Equal(t, sdData, data, "Get should return SD blob when no regular blob exists")
	})

	// Test concurrent access
	t.Run("ConcurrentAccess", func(t *testing.T) {
		store := NewMemoryStore()
		const testHash = "f2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e67"
		testData := []byte("concurrent test data")
		
		libtesting.TestConcurrentAccess(
			t,
			store,
			testHash,
			testData,
			func(i int) string { return fmt.Sprintf("%096x", i+1) },
			func(i int) []byte { return []byte(fmt.Sprintf("data_%d", i)) },
			100,
			10,
		)
	})

	// Test concurrent access with different parameters
	t.Run("ConcurrentAccess_HighConcurrency", func(t *testing.T) {
		store := NewMemoryStore()
		const testHash = "f2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e67"
		testData := []byte("concurrent test data")
		
		libtesting.TestConcurrentAccess(
			t,
			store,
			testHash,
			testData,
			func(i int) string { return fmt.Sprintf("%096x", i+1) },
			func(i int) []byte { return []byte(fmt.Sprintf("data_%d", i)) },
			500,
			20,
		)
	})

	t.Run("ConcurrentAccess_LowConcurrency", func(t *testing.T) {
		store := NewMemoryStore()
		const testHash = "f2f1841bb9c5f3b583ac3b8c07ee1a5bf9cc48923721c30d5ca6318615776c284e8936d72fa4db7fdda2e4e9598b1e67"
		testData := []byte("concurrent test data")
		
		libtesting.TestConcurrentAccess(
			t,
			store,
			testHash,
			testData,
			func(i int) string { return fmt.Sprintf("%096x", i+1) },
			func(i int) []byte { return []byte(fmt.Sprintf("data_%d", i)) },
			50,
			2,
		)
	})

	// Test defensive copies (copy-on-write/read)
	t.Run("DefensiveCopies", func(t *testing.T) {
		store := NewMemoryStore()
		hash := "7c9675ad7f40f29dcd41883ed9cf7e145bbb13976d9b83ab9354f4f61a87f0f7771a56724c2aa7a5ab43c68d7942e5d2"
		original := []byte("original")
		data := append([]byte(nil), original...) // make a separate slice to mutate later
		require.NoError(t, store.Put(hash, data))
		// Mutate caller's slice after Put; store should be unaffected
		data[0] = 'X'
		got1, err := store.Get(hash)
		require.NoError(t, err)
		assert.Equal(t, original, got1)
		// Mutate result of Get; store should still be unaffected
		got1[1] = 'Y'
		got2, err := store.Get(hash)
		require.NoError(t, err)
		assert.Equal(t, original, got2)
	})

}
