// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coordinator

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
	"go.uber.org/zap"
)

// NewMockRequestCoordinator creates a new instance of MockRequestCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestCoordinator {
	mock := &MockRequestCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestCoordinator is an autogenerated mock type for the RequestCoordinator type
type MockRequestCoordinator struct {
	mock.Mock
}

type MockRequestCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestCoordinator) EXPECT() *MockRequestCoordinator_Expecter {
	return &MockRequestCoordinator_Expecter{mock: &_m.Mock}
}

// CompleteWithData provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) CompleteWithData(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string) {
	_mock.Called(req, data, raceCancel, hash)
	return
}

// MockRequestCoordinator_CompleteWithData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithData'
type MockRequestCoordinator_CompleteWithData_Call struct {
	*mock.Call
}

// CompleteWithData is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - data []byte
//   - raceCancel context.CancelFunc
//   - hash string
func (_e *MockRequestCoordinator_Expecter) CompleteWithData(req interface{}, data interface{}, raceCancel interface{}, hash interface{}) *MockRequestCoordinator_CompleteWithData_Call {
	return &MockRequestCoordinator_CompleteWithData_Call{Call: _e.mock.On("CompleteWithData", req, data, raceCancel, hash)}
}

func (_c *MockRequestCoordinator_CompleteWithData_Call) Run(run func(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string)) *MockRequestCoordinator_CompleteWithData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 context.CancelFunc
		if args[2] != nil {
			arg2 = args[2].(context.CancelFunc)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithData_Call) Return() *MockRequestCoordinator_CompleteWithData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithData_Call) RunAndReturn(run func(req *blob.BlobRequest, data []byte, raceCancel context.CancelFunc, hash string)) *MockRequestCoordinator_CompleteWithData_Call {
	_c.Run(run)
	return _c
}

// CompleteWithError provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) CompleteWithError(req *blob.BlobRequest, err error) error {
	ret := _mock.Called(req, err)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWithError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) error); ok {
		r0 = returnFunc(req, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRequestCoordinator_CompleteWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithError'
type MockRequestCoordinator_CompleteWithError_Call struct {
	*mock.Call
}

// CompleteWithError is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
func (_e *MockRequestCoordinator_Expecter) CompleteWithError(req interface{}, err interface{}) *MockRequestCoordinator_CompleteWithError_Call {
	return &MockRequestCoordinator_CompleteWithError_Call{Call: _e.mock.On("CompleteWithError", req, err)}
}

func (_c *MockRequestCoordinator_CompleteWithError_Call) Run(run func(req *blob.BlobRequest, err error)) *MockRequestCoordinator_CompleteWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithError_Call) Return(err1 error) *MockRequestCoordinator_CompleteWithError_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithError_Call) RunAndReturn(run func(req *blob.BlobRequest, err error) error) *MockRequestCoordinator_CompleteWithError_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWithErrorAndCancel provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) CompleteWithErrorAndCancel(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string) {
	_mock.Called(req, err, raceCancel, hash)
	return
}

// MockRequestCoordinator_CompleteWithErrorAndCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithErrorAndCancel'
type MockRequestCoordinator_CompleteWithErrorAndCancel_Call struct {
	*mock.Call
}

// CompleteWithErrorAndCancel is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
//   - raceCancel context.CancelFunc
//   - hash string
func (_e *MockRequestCoordinator_Expecter) CompleteWithErrorAndCancel(req interface{}, err interface{}, raceCancel interface{}, hash interface{}) *MockRequestCoordinator_CompleteWithErrorAndCancel_Call {
	return &MockRequestCoordinator_CompleteWithErrorAndCancel_Call{Call: _e.mock.On("CompleteWithErrorAndCancel", req, err, raceCancel, hash)}
}

func (_c *MockRequestCoordinator_CompleteWithErrorAndCancel_Call) Run(run func(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string)) *MockRequestCoordinator_CompleteWithErrorAndCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 context.CancelFunc
		if args[2] != nil {
			arg2 = args[2].(context.CancelFunc)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithErrorAndCancel_Call) Return() *MockRequestCoordinator_CompleteWithErrorAndCancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_CompleteWithErrorAndCancel_Call) RunAndReturn(run func(req *blob.BlobRequest, err error, raceCancel context.CancelFunc, hash string)) *MockRequestCoordinator_CompleteWithErrorAndCancel_Call {
	_c.Run(run)
	return _c
}

// GetBacklogSize provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) GetBacklogSize() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBacklogSize")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRequestCoordinator_GetBacklogSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBacklogSize'
type MockRequestCoordinator_GetBacklogSize_Call struct {
	*mock.Call
}

// GetBacklogSize is a helper method to define mock.On call
func (_e *MockRequestCoordinator_Expecter) GetBacklogSize() *MockRequestCoordinator_GetBacklogSize_Call {
	return &MockRequestCoordinator_GetBacklogSize_Call{Call: _e.mock.On("GetBacklogSize")}
}

func (_c *MockRequestCoordinator_GetBacklogSize_Call) Run(run func()) *MockRequestCoordinator_GetBacklogSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestCoordinator_GetBacklogSize_Call) Return(n int) *MockRequestCoordinator_GetBacklogSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRequestCoordinator_GetBacklogSize_Call) RunAndReturn(run func() int) *MockRequestCoordinator_GetBacklogSize_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateRequest provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) GetOrCreateRequest(hash string) (*blob.BlobRequest, bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateRequest")
	}

	var r0 *blob.BlobRequest
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*blob.BlobRequest, bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *blob.BlobRequest); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blob.BlobRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRequestCoordinator_GetOrCreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateRequest'
type MockRequestCoordinator_GetOrCreateRequest_Call struct {
	*mock.Call
}

// GetOrCreateRequest is a helper method to define mock.On call
//   - hash string
func (_e *MockRequestCoordinator_Expecter) GetOrCreateRequest(hash interface{}) *MockRequestCoordinator_GetOrCreateRequest_Call {
	return &MockRequestCoordinator_GetOrCreateRequest_Call{Call: _e.mock.On("GetOrCreateRequest", hash)}
}

func (_c *MockRequestCoordinator_GetOrCreateRequest_Call) Run(run func(hash string)) *MockRequestCoordinator_GetOrCreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_GetOrCreateRequest_Call) Return(blobRequest *blob.BlobRequest, b bool, err error) *MockRequestCoordinator_GetOrCreateRequest_Call {
	_c.Call.Return(blobRequest, b, err)
	return _c
}

func (_c *MockRequestCoordinator_GetOrCreateRequest_Call) RunAndReturn(run func(hash string) (*blob.BlobRequest, bool, error)) *MockRequestCoordinator_GetOrCreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestState provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) GetRequestState(req *blob.BlobRequest) (int32, int32, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestState")
	}

	var r0 int32
	var r1 int32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest) (int32, int32, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest) int32); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(*blob.BlobRequest) int32); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Get(1).(int32)
	}
	if returnFunc, ok := ret.Get(2).(func(*blob.BlobRequest) error); ok {
		r2 = returnFunc(req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRequestCoordinator_GetRequestState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestState'
type MockRequestCoordinator_GetRequestState_Call struct {
	*mock.Call
}

// GetRequestState is a helper method to define mock.On call
//   - req *blob.BlobRequest
func (_e *MockRequestCoordinator_Expecter) GetRequestState(req interface{}) *MockRequestCoordinator_GetRequestState_Call {
	return &MockRequestCoordinator_GetRequestState_Call{Call: _e.mock.On("GetRequestState", req)}
}

func (_c *MockRequestCoordinator_GetRequestState_Call) Run(run func(req *blob.BlobRequest)) *MockRequestCoordinator_GetRequestState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_GetRequestState_Call) Return(n int32, n1 int32, err error) *MockRequestCoordinator_GetRequestState_Call {
	_c.Call.Return(n, n1, err)
	return _c
}

func (_c *MockRequestCoordinator_GetRequestState_Call) RunAndReturn(run func(req *blob.BlobRequest) (int32, int32, error)) *MockRequestCoordinator_GetRequestState_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeRequest provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) InitializeRequest(req *blob.BlobRequest, raceCancel context.CancelFunc, totalPeers int32) {
	_mock.Called(req, raceCancel, totalPeers)
	return
}

// MockRequestCoordinator_InitializeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeRequest'
type MockRequestCoordinator_InitializeRequest_Call struct {
	*mock.Call
}

// InitializeRequest is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - raceCancel context.CancelFunc
//   - totalPeers int32
func (_e *MockRequestCoordinator_Expecter) InitializeRequest(req interface{}, raceCancel interface{}, totalPeers interface{}) *MockRequestCoordinator_InitializeRequest_Call {
	return &MockRequestCoordinator_InitializeRequest_Call{Call: _e.mock.On("InitializeRequest", req, raceCancel, totalPeers)}
}

func (_c *MockRequestCoordinator_InitializeRequest_Call) Run(run func(req *blob.BlobRequest, raceCancel context.CancelFunc, totalPeers int32)) *MockRequestCoordinator_InitializeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 context.CancelFunc
		if args[1] != nil {
			arg1 = args[1].(context.CancelFunc)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_InitializeRequest_Call) Return() *MockRequestCoordinator_InitializeRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_InitializeRequest_Call) RunAndReturn(run func(req *blob.BlobRequest, raceCancel context.CancelFunc, totalPeers int32)) *MockRequestCoordinator_InitializeRequest_Call {
	_c.Run(run)
	return _c
}

// IsStopped provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRequestCoordinator_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockRequestCoordinator_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockRequestCoordinator_Expecter) IsStopped() *MockRequestCoordinator_IsStopped_Call {
	return &MockRequestCoordinator_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockRequestCoordinator_IsStopped_Call) Run(run func()) *MockRequestCoordinator_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestCoordinator_IsStopped_Call) Return(b bool) *MockRequestCoordinator_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRequestCoordinator_IsStopped_Call) RunAndReturn(run func() bool) *MockRequestCoordinator_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRequest provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) RemoveRequest(hash string) {
	_mock.Called(hash)
	return
}

// MockRequestCoordinator_RemoveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRequest'
type MockRequestCoordinator_RemoveRequest_Call struct {
	*mock.Call
}

// RemoveRequest is a helper method to define mock.On call
//   - hash string
func (_e *MockRequestCoordinator_Expecter) RemoveRequest(hash interface{}) *MockRequestCoordinator_RemoveRequest_Call {
	return &MockRequestCoordinator_RemoveRequest_Call{Call: _e.mock.On("RemoveRequest", hash)}
}

func (_c *MockRequestCoordinator_RemoveRequest_Call) Run(run func(hash string)) *MockRequestCoordinator_RemoveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_RemoveRequest_Call) Return() *MockRequestCoordinator_RemoveRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_RemoveRequest_Call) RunAndReturn(run func(hash string)) *MockRequestCoordinator_RemoveRequest_Call {
	_c.Run(run)
	return _c
}

// ResetForNewPhase provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) ResetForNewPhase(req *blob.BlobRequest, newTotalPeers int32) {
	_mock.Called(req, newTotalPeers)
	return
}

// MockRequestCoordinator_ResetForNewPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetForNewPhase'
type MockRequestCoordinator_ResetForNewPhase_Call struct {
	*mock.Call
}

// ResetForNewPhase is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - newTotalPeers int32
func (_e *MockRequestCoordinator_Expecter) ResetForNewPhase(req interface{}, newTotalPeers interface{}) *MockRequestCoordinator_ResetForNewPhase_Call {
	return &MockRequestCoordinator_ResetForNewPhase_Call{Call: _e.mock.On("ResetForNewPhase", req, newTotalPeers)}
}

func (_c *MockRequestCoordinator_ResetForNewPhase_Call) Run(run func(req *blob.BlobRequest, newTotalPeers int32)) *MockRequestCoordinator_ResetForNewPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_ResetForNewPhase_Call) Return() *MockRequestCoordinator_ResetForNewPhase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_ResetForNewPhase_Call) RunAndReturn(run func(req *blob.BlobRequest, newTotalPeers int32)) *MockRequestCoordinator_ResetForNewPhase_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) SetLogger(logger *zap.Logger) {
	_mock.Called(logger)
	return
}

// MockRequestCoordinator_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockRequestCoordinator_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *zap.Logger
func (_e *MockRequestCoordinator_Expecter) SetLogger(logger interface{}) *MockRequestCoordinator_SetLogger_Call {
	return &MockRequestCoordinator_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockRequestCoordinator_SetLogger_Call) Run(run func(logger *zap.Logger)) *MockRequestCoordinator_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zap.Logger
		if args[0] != nil {
			arg0 = args[0].(*zap.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_SetLogger_Call) Return() *MockRequestCoordinator_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_SetLogger_Call) RunAndReturn(run func(logger *zap.Logger)) *MockRequestCoordinator_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) Start() {
	_mock.Called()
	return
}

// MockRequestCoordinator_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRequestCoordinator_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockRequestCoordinator_Expecter) Start() *MockRequestCoordinator_Start_Call {
	return &MockRequestCoordinator_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockRequestCoordinator_Start_Call) Run(run func()) *MockRequestCoordinator_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestCoordinator_Start_Call) Return() *MockRequestCoordinator_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_Start_Call) RunAndReturn(run func()) *MockRequestCoordinator_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) Stop() {
	_mock.Called()
	return
}

// MockRequestCoordinator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRequestCoordinator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockRequestCoordinator_Expecter) Stop() *MockRequestCoordinator_Stop_Call {
	return &MockRequestCoordinator_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockRequestCoordinator_Stop_Call) Run(run func()) *MockRequestCoordinator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestCoordinator_Stop_Call) Return() *MockRequestCoordinator_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestCoordinator_Stop_Call) RunAndReturn(run func()) *MockRequestCoordinator_Stop_Call {
	_c.Run(run)
	return _c
}

// TrackFailedPeer provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) TrackFailedPeer(req *blob.BlobRequest, err error) (int32, bool) {
	ret := _mock.Called(req, err)

	if len(ret) == 0 {
		panic("no return value specified for TrackFailedPeer")
	}

	var r0 int32
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) (int32, bool)); ok {
		return returnFunc(req, err)
	}
	if returnFunc, ok := ret.Get(0).(func(*blob.BlobRequest, error) int32); ok {
		r0 = returnFunc(req, err)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(*blob.BlobRequest, error) bool); ok {
		r1 = returnFunc(req, err)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRequestCoordinator_TrackFailedPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackFailedPeer'
type MockRequestCoordinator_TrackFailedPeer_Call struct {
	*mock.Call
}

// TrackFailedPeer is a helper method to define mock.On call
//   - req *blob.BlobRequest
//   - err error
func (_e *MockRequestCoordinator_Expecter) TrackFailedPeer(req interface{}, err interface{}) *MockRequestCoordinator_TrackFailedPeer_Call {
	return &MockRequestCoordinator_TrackFailedPeer_Call{Call: _e.mock.On("TrackFailedPeer", req, err)}
}

func (_c *MockRequestCoordinator_TrackFailedPeer_Call) Run(run func(req *blob.BlobRequest, err error)) *MockRequestCoordinator_TrackFailedPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blob.BlobRequest
		if args[0] != nil {
			arg0 = args[0].(*blob.BlobRequest)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_TrackFailedPeer_Call) Return(n int32, b bool) *MockRequestCoordinator_TrackFailedPeer_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *MockRequestCoordinator_TrackFailedPeer_Call) RunAndReturn(run func(req *blob.BlobRequest, err error) (int32, bool)) *MockRequestCoordinator_TrackFailedPeer_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForResult provides a mock function for the type MockRequestCoordinator
func (_mock *MockRequestCoordinator) WaitForResult(ctx context.Context, req *blob.BlobRequest) ([]byte, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for WaitForResult")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *blob.BlobRequest) ([]byte, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *blob.BlobRequest) []byte); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *blob.BlobRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestCoordinator_WaitForResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForResult'
type MockRequestCoordinator_WaitForResult_Call struct {
	*mock.Call
}

// WaitForResult is a helper method to define mock.On call
//   - ctx context.Context
//   - req *blob.BlobRequest
func (_e *MockRequestCoordinator_Expecter) WaitForResult(ctx interface{}, req interface{}) *MockRequestCoordinator_WaitForResult_Call {
	return &MockRequestCoordinator_WaitForResult_Call{Call: _e.mock.On("WaitForResult", ctx, req)}
}

func (_c *MockRequestCoordinator_WaitForResult_Call) Run(run func(ctx context.Context, req *blob.BlobRequest)) *MockRequestCoordinator_WaitForResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *blob.BlobRequest
		if args[1] != nil {
			arg1 = args[1].(*blob.BlobRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestCoordinator_WaitForResult_Call) Return(bytes []byte, err error) *MockRequestCoordinator_WaitForResult_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRequestCoordinator_WaitForResult_Call) RunAndReturn(run func(ctx context.Context, req *blob.BlobRequest) ([]byte, error)) *MockRequestCoordinator_WaitForResult_Call {
	_c.Call.Return(run)
	return _c
}
