// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coordinator

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht"
	"go.lumeweb.com/lbry-dht/bits"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/blob"
	"go.lumeweb.com/liblbry/blob/transfer/peer_transfer/executor"
	"go.uber.org/zap"
)

// NewMockPeerRaceCoordinator creates a new instance of MockPeerRaceCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerRaceCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerRaceCoordinator {
	mock := &MockPeerRaceCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerRaceCoordinator is an autogenerated mock type for the PeerRaceCoordinator type
type MockPeerRaceCoordinator struct {
	mock.Mock
}

type MockPeerRaceCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerRaceCoordinator) EXPECT() *MockPeerRaceCoordinator_Expecter {
	return &MockPeerRaceCoordinator_Expecter{mock: &_m.Mock}
}

// ExecuteRace provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) ExecuteRace(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest, completeOnFailure bool) ([]byte, error) {
	ret := _mock.Called(ctx, hash, contacts, hashBitmap, req, completeOnFailure)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteRace")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []dht.Contact, bits.Bitmap, *blob.BlobRequest, bool) ([]byte, error)); ok {
		return returnFunc(ctx, hash, contacts, hashBitmap, req, completeOnFailure)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []dht.Contact, bits.Bitmap, *blob.BlobRequest, bool) []byte); ok {
		r0 = returnFunc(ctx, hash, contacts, hashBitmap, req, completeOnFailure)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []dht.Contact, bits.Bitmap, *blob.BlobRequest, bool) error); ok {
		r1 = returnFunc(ctx, hash, contacts, hashBitmap, req, completeOnFailure)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerRaceCoordinator_ExecuteRace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteRace'
type MockPeerRaceCoordinator_ExecuteRace_Call struct {
	*mock.Call
}

// ExecuteRace is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - contacts []dht.Contact
//   - hashBitmap bits.Bitmap
//   - req *blob.BlobRequest
//   - completeOnFailure bool
func (_e *MockPeerRaceCoordinator_Expecter) ExecuteRace(ctx interface{}, hash interface{}, contacts interface{}, hashBitmap interface{}, req interface{}, completeOnFailure interface{}) *MockPeerRaceCoordinator_ExecuteRace_Call {
	return &MockPeerRaceCoordinator_ExecuteRace_Call{Call: _e.mock.On("ExecuteRace", ctx, hash, contacts, hashBitmap, req, completeOnFailure)}
}

func (_c *MockPeerRaceCoordinator_ExecuteRace_Call) Run(run func(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest, completeOnFailure bool)) *MockPeerRaceCoordinator_ExecuteRace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []dht.Contact
		if args[2] != nil {
			arg2 = args[2].([]dht.Contact)
		}
		var arg3 bits.Bitmap
		if args[3] != nil {
			arg3 = args[3].(bits.Bitmap)
		}
		var arg4 *blob.BlobRequest
		if args[4] != nil {
			arg4 = args[4].(*blob.BlobRequest)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_ExecuteRace_Call) Return(bytes []byte, err error) *MockPeerRaceCoordinator_ExecuteRace_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPeerRaceCoordinator_ExecuteRace_Call) RunAndReturn(run func(ctx context.Context, hash string, contacts []dht.Contact, hashBitmap bits.Bitmap, req *blob.BlobRequest, completeOnFailure bool) ([]byte, error)) *MockPeerRaceCoordinator_ExecuteRace_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoordinator provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) GetCoordinator() RequestCoordinator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoordinator")
	}

	var r0 RequestCoordinator
	if returnFunc, ok := ret.Get(0).(func() RequestCoordinator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RequestCoordinator)
		}
	}
	return r0
}

// MockPeerRaceCoordinator_GetCoordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoordinator'
type MockPeerRaceCoordinator_GetCoordinator_Call struct {
	*mock.Call
}

// GetCoordinator is a helper method to define mock.On call
func (_e *MockPeerRaceCoordinator_Expecter) GetCoordinator() *MockPeerRaceCoordinator_GetCoordinator_Call {
	return &MockPeerRaceCoordinator_GetCoordinator_Call{Call: _e.mock.On("GetCoordinator")}
}

func (_c *MockPeerRaceCoordinator_GetCoordinator_Call) Run(run func()) *MockPeerRaceCoordinator_GetCoordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_GetCoordinator_Call) Return(requestCoordinator RequestCoordinator) *MockPeerRaceCoordinator_GetCoordinator_Call {
	_c.Call.Return(requestCoordinator)
	return _c
}

func (_c *MockPeerRaceCoordinator_GetCoordinator_Call) RunAndReturn(run func() RequestCoordinator) *MockPeerRaceCoordinator_GetCoordinator_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskExecutor provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) GetTaskExecutor() executor.PeerTaskExecutor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTaskExecutor")
	}

	var r0 executor.PeerTaskExecutor
	if returnFunc, ok := ret.Get(0).(func() executor.PeerTaskExecutor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(executor.PeerTaskExecutor)
		}
	}
	return r0
}

// MockPeerRaceCoordinator_GetTaskExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskExecutor'
type MockPeerRaceCoordinator_GetTaskExecutor_Call struct {
	*mock.Call
}

// GetTaskExecutor is a helper method to define mock.On call
func (_e *MockPeerRaceCoordinator_Expecter) GetTaskExecutor() *MockPeerRaceCoordinator_GetTaskExecutor_Call {
	return &MockPeerRaceCoordinator_GetTaskExecutor_Call{Call: _e.mock.On("GetTaskExecutor")}
}

func (_c *MockPeerRaceCoordinator_GetTaskExecutor_Call) Run(run func()) *MockPeerRaceCoordinator_GetTaskExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_GetTaskExecutor_Call) Return(peerTaskExecutor executor.PeerTaskExecutor) *MockPeerRaceCoordinator_GetTaskExecutor_Call {
	_c.Call.Return(peerTaskExecutor)
	return _c
}

func (_c *MockPeerRaceCoordinator_GetTaskExecutor_Call) RunAndReturn(run func() executor.PeerTaskExecutor) *MockPeerRaceCoordinator_GetTaskExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerRaceCoordinator_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockPeerRaceCoordinator_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockPeerRaceCoordinator_Expecter) IsStopped() *MockPeerRaceCoordinator_IsStopped_Call {
	return &MockPeerRaceCoordinator_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockPeerRaceCoordinator_IsStopped_Call) Run(run func()) *MockPeerRaceCoordinator_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_IsStopped_Call) Return(b bool) *MockPeerRaceCoordinator_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerRaceCoordinator_IsStopped_Call) RunAndReturn(run func() bool) *MockPeerRaceCoordinator_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogger provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) SetLogger(logger *zap.Logger) {
	_mock.Called(logger)
	return
}

// MockPeerRaceCoordinator_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockPeerRaceCoordinator_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *zap.Logger
func (_e *MockPeerRaceCoordinator_Expecter) SetLogger(logger interface{}) *MockPeerRaceCoordinator_SetLogger_Call {
	return &MockPeerRaceCoordinator_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockPeerRaceCoordinator_SetLogger_Call) Run(run func(logger *zap.Logger)) *MockPeerRaceCoordinator_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zap.Logger
		if args[0] != nil {
			arg0 = args[0].(*zap.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_SetLogger_Call) Return() *MockPeerRaceCoordinator_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerRaceCoordinator_SetLogger_Call) RunAndReturn(run func(logger *zap.Logger)) *MockPeerRaceCoordinator_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetTimeout provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) SetTimeout(timeout time.Duration) {
	_mock.Called(timeout)
	return
}

// MockPeerRaceCoordinator_SetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeout'
type MockPeerRaceCoordinator_SetTimeout_Call struct {
	*mock.Call
}

// SetTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockPeerRaceCoordinator_Expecter) SetTimeout(timeout interface{}) *MockPeerRaceCoordinator_SetTimeout_Call {
	return &MockPeerRaceCoordinator_SetTimeout_Call{Call: _e.mock.On("SetTimeout", timeout)}
}

func (_c *MockPeerRaceCoordinator_SetTimeout_Call) Run(run func(timeout time.Duration)) *MockPeerRaceCoordinator_SetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_SetTimeout_Call) Return() *MockPeerRaceCoordinator_SetTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerRaceCoordinator_SetTimeout_Call) RunAndReturn(run func(timeout time.Duration)) *MockPeerRaceCoordinator_SetTimeout_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) Start() {
	_mock.Called()
	return
}

// MockPeerRaceCoordinator_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPeerRaceCoordinator_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPeerRaceCoordinator_Expecter) Start() *MockPeerRaceCoordinator_Start_Call {
	return &MockPeerRaceCoordinator_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPeerRaceCoordinator_Start_Call) Run(run func()) *MockPeerRaceCoordinator_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_Start_Call) Return() *MockPeerRaceCoordinator_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerRaceCoordinator_Start_Call) RunAndReturn(run func()) *MockPeerRaceCoordinator_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockPeerRaceCoordinator
func (_mock *MockPeerRaceCoordinator) Stop() {
	_mock.Called()
	return
}

// MockPeerRaceCoordinator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPeerRaceCoordinator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPeerRaceCoordinator_Expecter) Stop() *MockPeerRaceCoordinator_Stop_Call {
	return &MockPeerRaceCoordinator_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPeerRaceCoordinator_Stop_Call) Run(run func()) *MockPeerRaceCoordinator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRaceCoordinator_Stop_Call) Return() *MockPeerRaceCoordinator_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerRaceCoordinator_Stop_Call) RunAndReturn(run func()) *MockPeerRaceCoordinator_Stop_Call {
	_c.Run(run)
	return _c
}
