// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionHandler creates a new instance of MockConnectionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionHandler {
	mock := &MockConnectionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionHandler is an autogenerated mock type for the ConnectionHandler type
type MockConnectionHandler struct {
	mock.Mock
}

type MockConnectionHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionHandler) EXPECT() *MockConnectionHandler_Expecter {
	return &MockConnectionHandler_Expecter{mock: &_m.Mock}
}

// HandleConnection provides a mock function for the type MockConnectionHandler
func (_mock *MockConnectionHandler) HandleConnection(conn net.Conn) {
	_mock.Called(conn)
	return
}

// MockConnectionHandler_HandleConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnection'
type MockConnectionHandler_HandleConnection_Call struct {
	*mock.Call
}

// HandleConnection is a helper method to define mock.On call
//   - conn net.Conn
func (_e *MockConnectionHandler_Expecter) HandleConnection(conn interface{}) *MockConnectionHandler_HandleConnection_Call {
	return &MockConnectionHandler_HandleConnection_Call{Call: _e.mock.On("HandleConnection", conn)}
}

func (_c *MockConnectionHandler_HandleConnection_Call) Run(run func(conn net.Conn)) *MockConnectionHandler_HandleConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionHandler_HandleConnection_Call) Return() *MockConnectionHandler_HandleConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionHandler_HandleConnection_Call) RunAndReturn(run func(conn net.Conn)) *MockConnectionHandler_HandleConnection_Call {
	_c.Run(run)
	return _c
}
