// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDHTAnnouncer creates a new instance of MockDHTAnnouncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDHTAnnouncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDHTAnnouncer {
	mock := &MockDHTAnnouncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDHTAnnouncer is an autogenerated mock type for the DHTAnnouncer type
type MockDHTAnnouncer struct {
	mock.Mock
}

type MockDHTAnnouncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDHTAnnouncer) EXPECT() *MockDHTAnnouncer_Expecter {
	return &MockDHTAnnouncer_Expecter{mock: &_m.Mock}
}

// AnnounceBlob provides a mock function for the type MockDHTAnnouncer
func (_mock *MockDHTAnnouncer) AnnounceBlob(hash string) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for AnnounceBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHTAnnouncer_AnnounceBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceBlob'
type MockDHTAnnouncer_AnnounceBlob_Call struct {
	*mock.Call
}

// AnnounceBlob is a helper method to define mock.On call
//   - hash string
func (_e *MockDHTAnnouncer_Expecter) AnnounceBlob(hash interface{}) *MockDHTAnnouncer_AnnounceBlob_Call {
	return &MockDHTAnnouncer_AnnounceBlob_Call{Call: _e.mock.On("AnnounceBlob", hash)}
}

func (_c *MockDHTAnnouncer_AnnounceBlob_Call) Run(run func(hash string)) *MockDHTAnnouncer_AnnounceBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTAnnouncer_AnnounceBlob_Call) Return(err error) *MockDHTAnnouncer_AnnounceBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHTAnnouncer_AnnounceBlob_Call) RunAndReturn(run func(hash string) error) *MockDHTAnnouncer_AnnounceBlob_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBlob provides a mock function for the type MockDHTAnnouncer
func (_mock *MockDHTAnnouncer) RemoveBlob(hash string) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHTAnnouncer_RemoveBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBlob'
type MockDHTAnnouncer_RemoveBlob_Call struct {
	*mock.Call
}

// RemoveBlob is a helper method to define mock.On call
//   - hash string
func (_e *MockDHTAnnouncer_Expecter) RemoveBlob(hash interface{}) *MockDHTAnnouncer_RemoveBlob_Call {
	return &MockDHTAnnouncer_RemoveBlob_Call{Call: _e.mock.On("RemoveBlob", hash)}
}

func (_c *MockDHTAnnouncer_RemoveBlob_Call) Run(run func(hash string)) *MockDHTAnnouncer_RemoveBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTAnnouncer_RemoveBlob_Call) Return(err error) *MockDHTAnnouncer_RemoveBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHTAnnouncer_RemoveBlob_Call) RunAndReturn(run func(hash string) error) *MockDHTAnnouncer_RemoveBlob_Call {
	_c.Call.Return(run)
	return _c
}
