// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/lbryio/lbry.go/v2/dht"
	"github.com/lbryio/lbry.go/v2/dht/bits"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDHTNode creates a new instance of MockDHTNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDHTNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDHTNode {
	mock := &MockDHTNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDHTNode is an autogenerated mock type for the DHTNode type
type MockDHTNode struct {
	mock.Mock
}

type MockDHTNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDHTNode) EXPECT() *MockDHTNode_Expecter {
	return &MockDHTNode_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Add(hash bits.Bitmap) {
	_mock.Called(hash)
	return
}

// MockDHTNode_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockDHTNode_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - hash bits.Bitmap
func (_e *MockDHTNode_Expecter) Add(hash interface{}) *MockDHTNode_Add_Call {
	return &MockDHTNode_Add_Call{Call: _e.mock.On("Add", hash)}
}

func (_c *MockDHTNode_Add_Call) Run(run func(hash bits.Bitmap)) *MockDHTNode_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bits.Bitmap
		if args[0] != nil {
			arg0 = args[0].(bits.Bitmap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTNode_Add_Call) Return() *MockDHTNode_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDHTNode_Add_Call) RunAndReturn(run func(hash bits.Bitmap)) *MockDHTNode_Add_Call {
	_c.Run(run)
	return _c
}

// Address provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDHTNode_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockDHTNode_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) Address() *MockDHTNode_Address_Call {
	return &MockDHTNode_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockDHTNode_Address_Call) Run(run func()) *MockDHTNode_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_Address_Call) Return(s string) *MockDHTNode_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDHTNode_Address_Call) RunAndReturn(run func() string) *MockDHTNode_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Get(hash bits.Bitmap) ([]dht.Contact, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []dht.Contact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bits.Bitmap) ([]dht.Contact, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(bits.Bitmap) []dht.Contact); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dht.Contact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bits.Bitmap) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDHTNode_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDHTNode_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - hash bits.Bitmap
func (_e *MockDHTNode_Expecter) Get(hash interface{}) *MockDHTNode_Get_Call {
	return &MockDHTNode_Get_Call{Call: _e.mock.On("Get", hash)}
}

func (_c *MockDHTNode_Get_Call) Run(run func(hash bits.Bitmap)) *MockDHTNode_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bits.Bitmap
		if args[0] != nil {
			arg0 = args[0].(bits.Bitmap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTNode_Get_Call) Return(contacts []dht.Contact, err error) *MockDHTNode_Get_Call {
	_c.Call.Return(contacts, err)
	return _c
}

func (_c *MockDHTNode_Get_Call) RunAndReturn(run func(hash bits.Bitmap) ([]dht.Contact, error)) *MockDHTNode_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoutingTableInfo provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) GetRoutingTableInfo() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoutingTableInfo")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDHTNode_GetRoutingTableInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoutingTableInfo'
type MockDHTNode_GetRoutingTableInfo_Call struct {
	*mock.Call
}

// GetRoutingTableInfo is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) GetRoutingTableInfo() *MockDHTNode_GetRoutingTableInfo_Call {
	return &MockDHTNode_GetRoutingTableInfo_Call{Call: _e.mock.On("GetRoutingTableInfo")}
}

func (_c *MockDHTNode_GetRoutingTableInfo_Call) Run(run func()) *MockDHTNode_GetRoutingTableInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_GetRoutingTableInfo_Call) Return(s string) *MockDHTNode_GetRoutingTableInfo_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDHTNode_GetRoutingTableInfo_Call) RunAndReturn(run func() string) *MockDHTNode_GetRoutingTableInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) ID() bits.Bitmap {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 bits.Bitmap
	if returnFunc, ok := ret.Get(0).(func() bits.Bitmap); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bits.Bitmap)
		}
	}
	return r0
}

// MockDHTNode_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockDHTNode_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) ID() *MockDHTNode_ID_Call {
	return &MockDHTNode_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockDHTNode_ID_Call) Run(run func()) *MockDHTNode_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_ID_Call) Return(bitmap bits.Bitmap) *MockDHTNode_ID_Call {
	_c.Call.Return(bitmap)
	return _c
}

func (_c *MockDHTNode_ID_Call) RunAndReturn(run func() bits.Bitmap) *MockDHTNode_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsJoined provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) IsJoined() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsJoined")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDHTNode_IsJoined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsJoined'
type MockDHTNode_IsJoined_Call struct {
	*mock.Call
}

// IsJoined is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) IsJoined() *MockDHTNode_IsJoined_Call {
	return &MockDHTNode_IsJoined_Call{Call: _e.mock.On("IsJoined")}
}

func (_c *MockDHTNode_IsJoined_Call) Run(run func()) *MockDHTNode_IsJoined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_IsJoined_Call) Return(b bool) *MockDHTNode_IsJoined_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDHTNode_IsJoined_Call) RunAndReturn(run func() bool) *MockDHTNode_IsJoined_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Ping(addr string) error {
	ret := _mock.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHTNode_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDHTNode_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - addr string
func (_e *MockDHTNode_Expecter) Ping(addr interface{}) *MockDHTNode_Ping_Call {
	return &MockDHTNode_Ping_Call{Call: _e.mock.On("Ping", addr)}
}

func (_c *MockDHTNode_Ping_Call) Run(run func(addr string)) *MockDHTNode_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTNode_Ping_Call) Return(err error) *MockDHTNode_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHTNode_Ping_Call) RunAndReturn(run func(addr string) error) *MockDHTNode_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Remove(hash bits.Bitmap) {
	_mock.Called(hash)
	return
}

// MockDHTNode_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockDHTNode_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - hash bits.Bitmap
func (_e *MockDHTNode_Expecter) Remove(hash interface{}) *MockDHTNode_Remove_Call {
	return &MockDHTNode_Remove_Call{Call: _e.mock.On("Remove", hash)}
}

func (_c *MockDHTNode_Remove_Call) Run(run func(hash bits.Bitmap)) *MockDHTNode_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bits.Bitmap
		if args[0] != nil {
			arg0 = args[0].(bits.Bitmap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHTNode_Remove_Call) Return() *MockDHTNode_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDHTNode_Remove_Call) RunAndReturn(run func(hash bits.Bitmap)) *MockDHTNode_Remove_Call {
	_c.Run(run)
	return _c
}

// Restart provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Restart() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHTNode_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockDHTNode_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) Restart() *MockDHTNode_Restart_Call {
	return &MockDHTNode_Restart_Call{Call: _e.mock.On("Restart")}
}

func (_c *MockDHTNode_Restart_Call) Run(run func()) *MockDHTNode_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_Restart_Call) Return(err error) *MockDHTNode_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHTNode_Restart_Call) RunAndReturn(run func() error) *MockDHTNode_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Shutdown() {
	_mock.Called()
	return
}

// MockDHTNode_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockDHTNode_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) Shutdown() *MockDHTNode_Shutdown_Call {
	return &MockDHTNode_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockDHTNode_Shutdown_Call) Run(run func()) *MockDHTNode_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_Shutdown_Call) Return() *MockDHTNode_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDHTNode_Shutdown_Call) RunAndReturn(run func()) *MockDHTNode_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHTNode_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDHTNode_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) Start() *MockDHTNode_Start_Call {
	return &MockDHTNode_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockDHTNode_Start_Call) Run(run func()) *MockDHTNode_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_Start_Call) Return(err error) *MockDHTNode_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHTNode_Start_Call) RunAndReturn(run func() error) *MockDHTNode_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) Wait() {
	_mock.Called()
	return
}

// MockDHTNode_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockDHTNode_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) Wait() *MockDHTNode_Wait_Call {
	return &MockDHTNode_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockDHTNode_Wait_Call) Run(run func()) *MockDHTNode_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_Wait_Call) Return() *MockDHTNode_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDHTNode_Wait_Call) RunAndReturn(run func()) *MockDHTNode_Wait_Call {
	_c.Run(run)
	return _c
}

// WaitUntilJoined provides a mock function for the type MockDHTNode
func (_mock *MockDHTNode) WaitUntilJoined() {
	_mock.Called()
	return
}

// MockDHTNode_WaitUntilJoined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUntilJoined'
type MockDHTNode_WaitUntilJoined_Call struct {
	*mock.Call
}

// WaitUntilJoined is a helper method to define mock.On call
func (_e *MockDHTNode_Expecter) WaitUntilJoined() *MockDHTNode_WaitUntilJoined_Call {
	return &MockDHTNode_WaitUntilJoined_Call{Call: _e.mock.On("WaitUntilJoined")}
}

func (_c *MockDHTNode_WaitUntilJoined_Call) Run(run func()) *MockDHTNode_WaitUntilJoined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTNode_WaitUntilJoined_Call) Return() *MockDHTNode_WaitUntilJoined_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDHTNode_WaitUntilJoined_Call) RunAndReturn(run func()) *MockDHTNode_WaitUntilJoined_Call {
	_c.Run(run)
	return _c
}
