// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/lbry-dht"
)

// NewMockDHTRoutable creates a new instance of MockDHTRoutable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDHTRoutable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDHTRoutable {
	mock := &MockDHTRoutable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDHTRoutable is an autogenerated mock type for the DHTRoutable type
type MockDHTRoutable struct {
	mock.Mock
}

type MockDHTRoutable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDHTRoutable) EXPECT() *MockDHTRoutable_Expecter {
	return &MockDHTRoutable_Expecter{mock: &_m.Mock}
}

// GetRoutingTable provides a mock function for the type MockDHTRoutable
func (_mock *MockDHTRoutable) GetRoutingTable() dht.RoutingTable {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoutingTable")
	}

	var r0 dht.RoutingTable
	if returnFunc, ok := ret.Get(0).(func() dht.RoutingTable); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dht.RoutingTable)
		}
	}
	return r0
}

// MockDHTRoutable_GetRoutingTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoutingTable'
type MockDHTRoutable_GetRoutingTable_Call struct {
	*mock.Call
}

// GetRoutingTable is a helper method to define mock.On call
func (_e *MockDHTRoutable_Expecter) GetRoutingTable() *MockDHTRoutable_GetRoutingTable_Call {
	return &MockDHTRoutable_GetRoutingTable_Call{Call: _e.mock.On("GetRoutingTable")}
}

func (_c *MockDHTRoutable_GetRoutingTable_Call) Run(run func()) *MockDHTRoutable_GetRoutingTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDHTRoutable_GetRoutingTable_Call) Return(routingTable dht.RoutingTable) *MockDHTRoutable_GetRoutingTable_Call {
	_c.Call.Return(routingTable)
	return _c
}

func (_c *MockDHTRoutable_GetRoutingTable_Call) RunAndReturn(run func() dht.RoutingTable) *MockDHTRoutable_GetRoutingTable_Call {
	_c.Call.Return(run)
	return _c
}
