// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNetworkCrawler creates a new instance of MockNetworkCrawler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkCrawler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkCrawler {
	mock := &MockNetworkCrawler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetworkCrawler is an autogenerated mock type for the NetworkCrawler type
type MockNetworkCrawler struct {
	mock.Mock
}

type MockNetworkCrawler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkCrawler) EXPECT() *MockNetworkCrawler_Expecter {
	return &MockNetworkCrawler_Expecter{mock: &_m.Mock}
}

// GetDuration provides a mock function for the type MockNetworkCrawler
func (_mock *MockNetworkCrawler) GetDuration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockNetworkCrawler_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockNetworkCrawler_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
func (_e *MockNetworkCrawler_Expecter) GetDuration() *MockNetworkCrawler_GetDuration_Call {
	return &MockNetworkCrawler_GetDuration_Call{Call: _e.mock.On("GetDuration")}
}

func (_c *MockNetworkCrawler_GetDuration_Call) Run(run func()) *MockNetworkCrawler_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkCrawler_GetDuration_Call) Return(duration time.Duration) *MockNetworkCrawler_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockNetworkCrawler_GetDuration_Call) RunAndReturn(run func() time.Duration) *MockNetworkCrawler_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockNetworkCrawler
func (_mock *MockNetworkCrawler) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNetworkCrawler_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockNetworkCrawler_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockNetworkCrawler_Expecter) Run() *MockNetworkCrawler_Run_Call {
	return &MockNetworkCrawler_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockNetworkCrawler_Run_Call) Run(run func()) *MockNetworkCrawler_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkCrawler_Run_Call) Return(err error) *MockNetworkCrawler_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNetworkCrawler_Run_Call) RunAndReturn(run func() error) *MockNetworkCrawler_Run_Call {
	_c.Call.Return(run)
	return _c
}
