// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNetworkCrawler creates a new instance of MockNetworkCrawler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkCrawler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkCrawler {
	mock := &MockNetworkCrawler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetworkCrawler is an autogenerated mock type for the NetworkCrawler type
type MockNetworkCrawler struct {
	mock.Mock
}

type MockNetworkCrawler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkCrawler) EXPECT() *MockNetworkCrawler_Expecter {
	return &MockNetworkCrawler_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockNetworkCrawler
func (_mock *MockNetworkCrawler) Run() {
	_mock.Called()
	return
}

// MockNetworkCrawler_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockNetworkCrawler_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockNetworkCrawler_Expecter) Run() *MockNetworkCrawler_Run_Call {
	return &MockNetworkCrawler_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockNetworkCrawler_Run_Call) Run(run func()) *MockNetworkCrawler_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkCrawler_Run_Call) Return() *MockNetworkCrawler_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNetworkCrawler_Run_Call) RunAndReturn(run func()) *MockNetworkCrawler_Run_Call {
	_c.Run(run)
	return _c
}
