// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/stream"
)

// NewMockPeerClient creates a new instance of MockPeerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerClient {
	mock := &MockPeerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerClient is an autogenerated mock type for the PeerClient type
type MockPeerClient struct {
	mock.Mock
}

// Reset provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) Reset() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerClient_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockPeerClient_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockPeerClient_Expecter) Reset() *MockPeerClient_Reset_Call {
	return &MockPeerClient_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockPeerClient_Reset_Call) Run(run func()) *MockPeerClient_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerClient_Reset_Call) Return(err error) *MockPeerClient_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerClient_Reset_Call) RunAndReturn(run func() error) *MockPeerClient_Reset_Call {
	_c.Call.Return(run)
	return _c
}

type MockPeerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerClient) EXPECT() *MockPeerClient_Expecter {
	return &MockPeerClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPeerClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPeerClient_Expecter) Close() *MockPeerClient_Close_Call {
	return &MockPeerClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPeerClient_Close_Call) Run(run func()) *MockPeerClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerClient_Close_Call) Return(err error) *MockPeerClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerClient_Close_Call) RunAndReturn(run func() error) *MockPeerClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) Connect(ctx context.Context, address string) error {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockPeerClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockPeerClient_Expecter) Connect(ctx interface{}, address interface{}) *MockPeerClient_Connect_Call {
	return &MockPeerClient_Connect_Call{Call: _e.mock.On("Connect", ctx, address)}
}

func (_c *MockPeerClient_Connect_Call) Run(run func(ctx context.Context, address string)) *MockPeerClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerClient_Connect_Call) Return(err error) *MockPeerClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerClient_Connect_Call) RunAndReturn(run func(ctx context.Context, address string) error) *MockPeerClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) GetBlob(ctx context.Context, hash string) ([]byte, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerClient_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type MockPeerClient_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockPeerClient_Expecter) GetBlob(ctx interface{}, hash interface{}) *MockPeerClient_GetBlob_Call {
	return &MockPeerClient_GetBlob_Call{Call: _e.mock.On("GetBlob", ctx, hash)}
}

func (_c *MockPeerClient_GetBlob_Call) Run(run func(ctx context.Context, hash string)) *MockPeerClient_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerClient_GetBlob_Call) Return(bytes []byte, err error) *MockPeerClient_GetBlob_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPeerClient_GetBlob_Call) RunAndReturn(run func(ctx context.Context, hash string) ([]byte, error)) *MockPeerClient_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetStream provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) GetStream(ctx context.Context, sdHash string) (stream.Stream, error) {
	ret := _mock.Called(ctx, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 stream.Stream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (stream.Stream, error)); ok {
		return returnFunc(ctx, sdHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) stream.Stream); ok {
		r0 = returnFunc(ctx, sdHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stream.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sdHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerClient_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type MockPeerClient_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - ctx context.Context
//   - sdHash string
func (_e *MockPeerClient_Expecter) GetStream(ctx interface{}, sdHash interface{}) *MockPeerClient_GetStream_Call {
	return &MockPeerClient_GetStream_Call{Call: _e.mock.On("GetStream", ctx, sdHash)}
}

func (_c *MockPeerClient_GetStream_Call) Run(run func(ctx context.Context, sdHash string)) *MockPeerClient_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerClient_GetStream_Call) Return(stream1 stream.Stream, err error) *MockPeerClient_GetStream_Call {
	_c.Call.Return(stream1, err)
	return _c
}

func (_c *MockPeerClient_GetStream_Call) RunAndReturn(run func(ctx context.Context, sdHash string) (stream.Stream, error)) *MockPeerClient_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// HasBlob provides a mock function for the type MockPeerClient
func (_mock *MockPeerClient) HasBlob(ctx context.Context, hash string) (bool, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for HasBlob")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerClient_HasBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBlob'
type MockPeerClient_HasBlob_Call struct {
	*mock.Call
}

// HasBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockPeerClient_Expecter) HasBlob(ctx interface{}, hash interface{}) *MockPeerClient_HasBlob_Call {
	return &MockPeerClient_HasBlob_Call{Call: _e.mock.On("HasBlob", ctx, hash)}
}

func (_c *MockPeerClient_HasBlob_Call) Run(run func(ctx context.Context, hash string)) *MockPeerClient_HasBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerClient_HasBlob_Call) Return(b bool, err error) *MockPeerClient_HasBlob_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPeerClient_HasBlob_Call) RunAndReturn(run func(ctx context.Context, hash string) (bool, error)) *MockPeerClient_HasBlob_Call {
	_c.Call.Return(run)
	return _c
}
