// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReflectorServer creates a new instance of MockReflectorServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReflectorServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReflectorServer {
	mock := &MockReflectorServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReflectorServer is an autogenerated mock type for the ReflectorServer type
type MockReflectorServer struct {
	mock.Mock
}

type MockReflectorServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReflectorServer) EXPECT() *MockReflectorServer_Expecter {
	return &MockReflectorServer_Expecter{mock: &_m.Mock}
}

// HandleConnection provides a mock function for the type MockReflectorServer
func (_mock *MockReflectorServer) HandleConnection(conn net.Conn) {
	_mock.Called(conn)
	return
}

// MockReflectorServer_HandleConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnection'
type MockReflectorServer_HandleConnection_Call struct {
	*mock.Call
}

// HandleConnection is a helper method to define mock.On call
//   - conn net.Conn
func (_e *MockReflectorServer_Expecter) HandleConnection(conn interface{}) *MockReflectorServer_HandleConnection_Call {
	return &MockReflectorServer_HandleConnection_Call{Call: _e.mock.On("HandleConnection", conn)}
}

func (_c *MockReflectorServer_HandleConnection_Call) Run(run func(conn net.Conn)) *MockReflectorServer_HandleConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReflectorServer_HandleConnection_Call) Return() *MockReflectorServer_HandleConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReflectorServer_HandleConnection_Call) RunAndReturn(run func(conn net.Conn)) *MockReflectorServer_HandleConnection_Call {
	_c.Run(run)
	return _c
}
