// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.16.0
// source: purchase.proto

package pb

import (
	fmt "fmt"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	io "io"
	slices "slices"
)

type Purchase struct {
	unknownFields []byte
	ClaimHash     []byte `protobuf:"bytes,1,opt,name=claim_hash,json=claimHash,proto3" json:"claimHash,omitempty"`
}

func (x *Purchase) Reset() {
	*x = Purchase{}
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) GetClaimHash() []byte {
	if x != nil {
		return x.ClaimHash
	}
	return nil
}

func (m *Purchase) CloneVT() *Purchase {
	if m == nil {
		return (*Purchase)(nil)
	}
	r := new(Purchase)
	r.ClaimHash = protobuf_go_lite.CloneBytes(m.ClaimHash)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Purchase) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Purchase) EqualVT(that *Purchase) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualBytes(this.ClaimHash, that.ClaimHash) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Purchase) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Purchase)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Purchase message to JSON.
func (x *Purchase) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.ClaimHash) > 0 || s.HasField("claimHash") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("claimHash")
		s.WriteBytes(x.ClaimHash)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Purchase to JSON.
func (x *Purchase) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Purchase message from JSON.
func (x *Purchase) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "claim_hash", "claimHash":
			s.AddField("claim_hash")
			x.ClaimHash = s.ReadBytes()
		}
	})
}

// UnmarshalJSON unmarshals the Purchase from JSON.
func (x *Purchase) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Purchase) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Purchase) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Purchase) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.ClaimHash) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.ClaimHash)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Purchase) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Purchase) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *Purchase) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.ClaimHash) > 0 {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.ClaimHash)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Purchase) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBytesNonEmpty(1, m.ClaimHash)
	n += len(m.unknownFields)
	return n
}

func (x *Purchase) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Purchase")
	if len(x.ClaimHash) != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "claim_hash")
		protobuf_go_lite.TextWriteBytes(&sb, x.ClaimHash)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Purchase) String() string {
	return x.MarshalProtoText()
}
func (m *Purchase) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Purchase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Purchase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimHash", wireType)
			}
			m.ClaimHash, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.ClaimHash, dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Purchase) UnmarshalVTUnsafe(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Purchase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Purchase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimHash", wireType)
			}
			m.ClaimHash, iNdEx, err = protobuf_go_lite.DecodeBytes(dAtA, iNdEx, false)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
