// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobManager creates a new instance of MockBlobManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobManager {
	mock := &MockBlobManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobManager is an autogenerated mock type for the BlobManager type
type MockBlobManager struct {
	mock.Mock
}

type MockBlobManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobManager) EXPECT() *MockBlobManager_Expecter {
	return &MockBlobManager_Expecter{mock: &_m.Mock}
}

// AddBlob provides a mock function for the type MockBlobManager
func (_mock *MockBlobManager) AddBlob(hash string, data []byte) error {
	ret := _mock.Called(hash, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(hash, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobManager_AddBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlob'
type MockBlobManager_AddBlob_Call struct {
	*mock.Call
}

// AddBlob is a helper method to define mock.On call
//   - hash string
//   - data []byte
func (_e *MockBlobManager_Expecter) AddBlob(hash interface{}, data interface{}) *MockBlobManager_AddBlob_Call {
	return &MockBlobManager_AddBlob_Call{Call: _e.mock.On("AddBlob", hash, data)}
}

func (_c *MockBlobManager_AddBlob_Call) Run(run func(hash string, data []byte)) *MockBlobManager_AddBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobManager_AddBlob_Call) Return(err error) *MockBlobManager_AddBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobManager_AddBlob_Call) RunAndReturn(run func(hash string, data []byte) error) *MockBlobManager_AddBlob_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBlob provides a mock function for the type MockBlobManager
func (_mock *MockBlobManager) RemoveBlob(hash string) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobManager_RemoveBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBlob'
type MockBlobManager_RemoveBlob_Call struct {
	*mock.Call
}

// RemoveBlob is a helper method to define mock.On call
//   - hash string
func (_e *MockBlobManager_Expecter) RemoveBlob(hash interface{}) *MockBlobManager_RemoveBlob_Call {
	return &MockBlobManager_RemoveBlob_Call{Call: _e.mock.On("RemoveBlob", hash)}
}

func (_c *MockBlobManager_RemoveBlob_Call) Run(run func(hash string)) *MockBlobManager_RemoveBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlobManager_RemoveBlob_Call) Return(err error) *MockBlobManager_RemoveBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobManager_RemoveBlob_Call) RunAndReturn(run func(hash string) error) *MockBlobManager_RemoveBlob_Call {
	_c.Call.Return(run)
	return _c
}
