// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockServer
func (_mock *MockServer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) Start(ctx interface{}) *MockServer_Start_Call {
	return &MockServer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockServer_Start_Call) Run(run func(ctx context.Context)) *MockServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_Start_Call) Return(err error) *MockServer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockServer
func (_mock *MockServer) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockServer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) Stop(ctx interface{}) *MockServer_Stop_Call {
	return &MockServer_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockServer_Stop_Call) Run(run func(ctx context.Context)) *MockServer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_Stop_Call) Return(err error) *MockServer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockServer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
